// Copies the long-form pages drafted in docs/content/*.md into the web app's
// own content source (src/content/pages.generated.ts), so the site never
// reads docs/ at runtime. Run after editing docs/content:
//   pnpm --filter @trading-dashboard/web content:sync
// `--check` fails when the generated file is stale (test/content.test.ts
// runs the same comparison).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

export const PAGES = ["about", "faq", "privacy", "terms", "delete-account"];
export const CONTENT_LOCALES = ["zh-TW", "en"];

const docs = new URL("../../../docs/content/", import.meta.url);
const target = new URL("../src/content/pages.generated.ts", import.meta.url);

const key = (page) => page.replace(/-(\w)/g, (_, c) => c.toUpperCase());

export function renderContentModule() {
  const lines = [
    "// Generated by scripts/sync-content.mjs from docs/content/*.md. Do not edit here:",
    "// edit docs/content, then run `pnpm --filter @trading-dashboard/web content:sync`.",
    "",
    "export const CONTENT_PAGES = {",
  ];
  for (const page of PAGES) {
    lines.push(`  ${key(page)}: {`);
    for (const locale of CONTENT_LOCALES) {
      const text = readFileSync(new URL(`${page}.${locale}.md`, docs), "utf8");
      lines.push(`    ${JSON.stringify(locale)}: ${JSON.stringify(text)},`);
    }
    lines.push("  },");
  }
  lines.push("} as const;", "");
  return lines.join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const next = renderContentModule();
  if (process.argv.includes("--check")) {
    if (readFileSync(target, "utf8") !== next) {
      console.error("src/content/pages.generated.ts is stale: run content:sync");
      process.exitCode = 1;
    }
  } else {
    writeFileSync(target, next);
    console.log(`Wrote ${fileURLToPath(target)}`);
  }
}
