// @vitest-environment happy-dom
import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { WalletsTable } from "@/components/insights/cohort-tables";
import { fixtureCohort } from "@/fixtures/discovery";
import { I18nProvider } from "@/i18n/provider";
import { catalogs } from "@/i18n/messages";
const viewport = vi.hoisted(() => ({ desktop: false }));
vi.mock("@/lib/use-is-desktop", () => ({ useIsDesktop: () => viewport.desktop }));
vi.mock("next/navigation", () => ({ useRouter: () => ({ push: vi.fn() }) }));
let root: Root, container: HTMLDivElement;
const base = fixtureCohort("profit").wallets[0]!;
const rows = Array.from({ length: 12 }, (_, i) => ({ ...base, address: `0x${String(i + 1).padStart(40, "0")}`, displayName: `Wallet ${i + 1}`, perpEquity: 1000 + i, totalPnl: 100 - i, roi: 0.1, leverage: 2.5, positionValue: 2000, sumUpnl: 7 }));
beforeEach(() => { Object.assign(globalThis, { IS_REACT_ACT_ENVIRONMENT: true }); viewport.desktop = false; container = document.createElement("div"); document.body.append(container); root = createRoot(container); });
afterEach(async () => { await act(async () => root.unmount()); container.remove(); });
const render = () => act(async () => root.render(<I18nProvider locale="en" messages={catalogs.en}><WalletsTable rows={rows} /></I18nProvider>));
const list = () => container.querySelector('[data-testid="cohort-wallets-mobile"]')!;
const pagerButton = (name: string) => [...container.querySelectorAll<HTMLButtonElement>("[data-pager] button")].find(b => b.textContent?.includes(name))!;
it("shows each mobile wallet's primary figures with complete secondary details on demand", async () => {
  await render();
  expect(list()).not.toBeNull();
  expect(container.querySelector("table")).toBeNull();
  const first = list().querySelector("li")!;
  expect(first.textContent).toContain("Wallet 12");
  for (const label of ["PNL", "ROI", "Perp Equity"]) expect(first.textContent).toContain(label);
  const toggle = first.querySelector<HTMLButtonElement>("button[aria-expanded]")!;
  expect(toggle.getAttribute("aria-expanded")).toBe("false");
  await act(async () => toggle.click());
  expect(toggle.getAttribute("aria-expanded")).toBe("true");
  const details = first.querySelector('[data-wallet-details]')!;
  for (const label of ["Traded Assets", "Copy Score", "Position Value", "Leverage", "UPNL", "Perp Bias"]) expect(details.textContent).toContain(label);
  expect(details.textContent).toContain("2.50×");
  expect(new URL(first.querySelector<HTMLAnchorElement>("a")!.href).pathname).toBe(`/en/trader/${rows[11].address}`);
  await act(async () => toggle.click());
  expect(first.querySelector('[data-wallet-details]')).toBeNull();
});
it("preserves all nine wallet sort choices, changes the actual order, and resets pagination on sort", async () => {
  await render();
  await act(async () => pagerButton("Next").click());
  expect(list().querySelectorAll("li")).toHaveLength(2);
  const select = container.querySelector<HTMLButtonElement>('[role="combobox"]')!;
  await act(async () => select.click());
  const options = [...document.querySelectorAll<HTMLElement>('[role="option"]')];
  expect(options).toHaveLength(9);
  const pnl = options.find(o => o.textContent?.trim() === "PNL")!;
  await act(async () => pnl.click());
  expect(list().querySelectorAll("li")).toHaveLength(10);
  expect(list().querySelector("li")!.textContent).toContain("Wallet 1");
  const direction = container.querySelector<HTMLButtonElement>('button[aria-label="Sort ascending"]')!;
  await act(async () => direction.click());
  expect(list().querySelector("li")!.textContent).toContain("Wallet 12");
});
it("retains the shared current page when resizing from mobile cards to the desktop table", async () => {
  await render();
  await act(async () => pagerButton("Next").click());
  expect(list().querySelectorAll("li")).toHaveLength(2);
  viewport.desktop = true; await render();
  expect(list()).toBeNull();
  expect(container.querySelectorAll("tbody tr")).toHaveLength(2);
  expect(container.querySelector("[data-pager]")!.textContent).toContain("Page 2");
});
