// @vitest-environment happy-dom
import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { beforeEach, afterEach, expect, it, vi } from 'vitest';
import { CopyLiveStrategySettings } from '@/components/settings/copy-live';
import { I18nProvider } from '@/i18n/provider';
import { catalogs } from '@/i18n/messages';
import { LOCALES, type Locale } from '@/i18n/config';
import { liveAccount, liveIntent, liveMandate, liveNow, liveOverview, liveOwner, liveSetup, liveStrategy } from './copy-live-fixtures';
const state = vi.hoisted(() => ({ get: vi.fn(), post: vi.fn(), sign: vi.fn(), status: 'signedIn', mode: 'privy', identity: 'owner@email', session: '1' }));
vi.mock('@/lib/auth', () => ({ useAuth: () => ({ ...state, wallet: { address: liveOwner, signTypedData: state.sign } }) }));
vi.mock('@/lib/api', () => ({ api: { get: state.get, post: state.post }, sessionKey: () => state.session }));
vi.mock('@/lib/query-policy', () => ({ defaultRetry: { retry: false } }));
vi.mock('next/navigation', () => ({ useRouter: () => ({ refresh() {} }) }));
let root: Root, container: HTMLDivElement, client: QueryClient, overview: ReturnType<typeof liveOverview>;
beforeEach(() => { Object.assign(globalThis, { IS_REACT_ACT_ENVIRONMENT: true }); Object.assign(state, { status: 'signedIn', mode: 'privy', identity: 'owner@email', session: '1' }); vi.spyOn(Date, 'now').mockReturnValue(liveNow); window.sessionStorage.clear(); state.get.mockReset(); state.post.mockReset(); state.sign.mockReset().mockResolvedValue(`0x${'aa'.repeat(65)}`); overview = liveOverview(); state.get.mockImplementation((path: string) => Promise.resolve(path === '/me/copy/live' ? overview : path === '/me/copy/agents' ? { available: true, network: 'testnet', setups: [liveSetup] } : { mandate: overview.mandates[0] ?? liveMandate, intent: liveIntent })); state.post.mockImplementation(async (path: string, body: { budgetUsd?: string }) => path.endsWith('/approve') ? { ...liveMandate, state: 'active', revision: 2 } : path.endsWith('/strategies') ? { ...liveStrategy, budgetUsd: body.budgetUsd } : { mandate: liveMandate, intent: liveIntent }); client = new QueryClient({ defaultOptions: { queries: { retry: false } } }); container = document.createElement('div'); document.body.append(container); root = createRoot(container); });
afterEach(async () => { await act(async () => root.unmount()); client.clear(); container.remove(); vi.restoreAllMocks(); });
async function settle() { await act(async () => { await new Promise(r => setTimeout(r, 25)); }); }
async function render(locale: Locale = 'en') { await act(async () => root.render(<QueryClientProvider client={client}><I18nProvider locale={locale} messages={catalogs[locale]}><CopyLiveStrategySettings accounts={[liveAccount]}/></I18nProvider></QueryClientProvider>)); await settle(); }
async function click(label: string) { const b = [...container.querySelectorAll('button')].find(b => b.textContent === label); expect(b).toBeTruthy(); await act(async () => b!.click()); await settle(); }
async function select() { await act(async () => { const el = container.querySelector('select[name="account"]')! as HTMLSelectElement; el.value = liveAccount.id; el.dispatchEvent(new Event('change', { bubbles: true })); }); await settle(); }
async function input(name: string, value: string) { await act(async () => { const el = container.querySelector(`input[name="${name}"]`)! as HTMLInputElement; const setter = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')!.set!; setter.call(el, value); el.dispatchEvent(new Event('input', { bubbles: true })); el.dispatchEvent(new Event('change', { bubbles: true })); }); await settle(); }
it('shows separate actual preparation and budget consent without paper equity or activation claims', async () => { await render(); expect(container.textContent).toContain('Budget authorization is not a deposit'); expect(container.textContent).toContain('Automatic execution is unavailable'); expect(state.post).not.toHaveBeenCalled(); expect(state.sign).not.toHaveBeenCalled(); expect(container.textContent).not.toContain('0%'); });
it('creates only an explicitly entered paused draft and preserves the exact budget string', async () => { overview = { ...overview, strategies: [], mandates: [] }; await render(); await input('leader', liveStrategy.leaderAddress); await input('budget', '100.000001'); await click('Prepare paused strategy'); expect(state.post.mock.calls[0][0]).toBe('/me/copy/live/strategies'); expect(state.post.mock.calls[0][1]).toMatchObject({ budgetUsd: '100.000001', sourceNetwork: 'testnet', settings: { direction: 'same', sizingMode: 'ratio', copyStartMode: 'delta' } }); expect(state.sign).not.toHaveBeenCalled(); });
it('requires original full intent review plus an explicit checkbox before exact local consent', async () => { await render(); await select(); expect(container.querySelector('article input[type="checkbox"]')).toBeNull(); await click('Review original consent'); expect(container.textContent).toContain(liveOwner); expect(container.textContent).toContain(liveSetup.agentAddress!); expect(container.textContent).toContain('100 USDC'); const approve = [...container.querySelectorAll('button')].find(b => b.textContent === 'Sign local consent')!; expect(approve.disabled).toBe(true); await act(async () => { (container.querySelector('article input[type="checkbox"]') as HTMLInputElement).click(); }); await click('Sign local consent'); expect(state.sign).toHaveBeenCalledOnce(); expect(state.post.mock.calls[0][0]).toBe('/me/copy/live/mandates/mandate/approve'); expect(container.textContent).toContain('Automatic execution is unavailable'); });
it('a lost consent response remains original read-only checking, never another signature or POST', async () => { state.post.mockRejectedValue(new Error('private-error')); await render(); await select(); await click('Review original consent'); await act(async () => { (container.querySelector('article input[type="checkbox"]') as HTMLInputElement).click(); }); await click('Sign local consent'); expect(container.textContent).toContain('Original request unconfirmed'); expect(container.textContent).not.toContain('private-error'); await click('Check original request'); expect(state.sign).toHaveBeenCalledOnce(); expect(state.post).toHaveBeenCalledOnce(); });
it('discarding the selected account during a held wallet prompt prevents approval', async () => { let finish!: (s: string) => void; state.sign.mockImplementation(() => new Promise(r => { finish = r; })); await render(); await select(); await click('Review original consent'); await act(async () => { (container.querySelector('article input[type="checkbox"]') as HTMLInputElement).click(); }); await click('Sign local consent'); state.session = 'changed'; await render(); await act(async () => finish(`0x${'aa'.repeat(65)}`)); await settle(); expect(state.post).not.toHaveBeenCalled(); expect(container.querySelector('select[name="account"]')?.getAttribute('value')).not.toBe(liveAccount.id); });
it.each([{ status: 'signedOut' }, { mode: 'fixture' }])('hides actual preparation and avoids reads under %j', async change => { Object.assign(state, change); await render(); expect(container.querySelector('section')).toBeNull(); expect(state.get).not.toHaveBeenCalled(); });
it.each(LOCALES)('renders translated actual preparation caveats and consent in %s', async locale => { await render(locale); expect(container.querySelector('section')?.getAttribute('aria-label')).toBeTruthy(); expect(container.textContent).not.toContain('copyLive.'); });
it('allows owner local revocation even after the agent is revoked, and uncertain revocation only reads the original record', async () => {
  overview = { ...overview, mandates: [{ ...liveMandate, state: 'active', revision: 2 }] };
  state.get.mockImplementation((path: string) => Promise.resolve(path === '/me/copy/live' ? overview : path === '/me/copy/agents' ? { available: true, network: 'testnet', setups: [{ ...liveSetup, state: 'revoked' }] } : { mandate: overview.mandates[0], intent: liveIntent }));
  state.post.mockRejectedValue(new Error('lost')); await render(); await select(); await click('Revoke local consent'); expect(state.post).toHaveBeenCalledOnce(); expect(container.textContent).toContain('Original request unconfirmed');
  await click('Check original request'); expect(state.post).toHaveBeenCalledOnce(); expect(state.sign).not.toHaveBeenCalled(); expect([...container.querySelectorAll('button')].some(b => b.textContent === 'Revoke local consent')).toBe(false);
});
