import { beforeEach, expect, it, vi } from 'vitest';
import * as live from '@/lib/copy-live';
import { liveContext, liveIntent, liveMandate, liveNow, liveOwner } from './copy-live-fixtures';
let memory: Map<string,string>, clock:number, owner:{status:string;mode:string;identity:string;session:string;walletAddress:string}, current: live.LiveConsentContext;
const expiredAt=liveNow+300000;
function original(eligible=true): live.LiveCopyChallenge & { renewal: NonNullable<live.LiveCopyChallenge['renewal']> } {return {mandate:structuredClone(liveMandate),intent:structuredClone(liveIntent),renewal:{checkedAt:new Date(clock).toISOString(),eligible,reason:eligible?'prepared_consent_expired' as const:null,mandateId:liveMandate.id,revision:1,nonce:liveNow}};}
function successor(){return {mandate:{...liveMandate,id:'successor',createdAt:new Date(clock).toISOString(),updatedAt:new Date(clock).toISOString()},intent:{...liveIntent,mandateId:'successor',nonce:clock,consentExpiresAt:clock+300000}};}
function journal(){return live.createLiveCopyJournal('renewal-owner',{getItem:k=>memory.get(k)??null,setItem:(k,v)=>{memory.set(k,v);}});}
function deps(){return {snapshot:()=>({...owner}),current:()=>current,now:()=>clock,journal:journal(),newKey:vi.fn(()=> 'successor_key_123456789'),challenge:vi.fn(async()=>original()),prepare:vi.fn(async(_id:string,_body:unknown,guard:()=>void)=>{guard();return successor();}),findMandate:vi.fn(async()=>successor()),sign:vi.fn(),approve:vi.fn()};}
beforeEach(()=>{memory=new Map();clock=expiredAt;owner={status:'signedIn',mode:'privy',identity:'owner',session:'1',walletAddress:liveOwner};current={...liveContext(),grant:{id:'grant',strategyId:liveMandate.strategyId,network:'testnet',accountAddress:liveMandate.accountAddress,signerAddress:liveIntent.agentAddress,status:'active',scopes:['copy:trade','copy:reduce'],expiresAt:liveMandate.expiresAt,revokedAt:null,version:1}};});
it('requires explicit renewal, fresh original server evidence and durable new key; never signs or approves',async()=>{const d=deps();d.journal.preparation({accountId:current.account.id,strategyId:current.strategy.id,accountAddress:current.account.address!,strategyVersion:1,key:'original_key_123456789',mandateId:liveMandate.id});d.journal.mark(liveMandate.id);d.prepare.mockImplementation(async(_id,_body,guard)=>{guard();expect([...memory.values()].join()).toContain('successor_key_123456789');return successor();});const result=await live.renewLiveCopyConsent(current,original(),d);expect(result.mandate.id).toBe('successor');expect(d.challenge).toHaveBeenCalledWith(liveMandate.id);expect(d.prepare).toHaveBeenCalledOnce();expect(d.sign).not.toHaveBeenCalled();expect(d.approve).not.toHaveBeenCalled();expect(journal().read().preparations[0].key).toBe('original_key_123456789');expect(journal().read().approvals).toContain(liveMandate.id);expect(journal().read().renewals[0]).toMatchObject({key:'successor_key_123456789',mandateId:'successor',predecessor:{id:liveMandate.id,revision:1,nonce:liveNow}});});
it('a lost new preparation only recovers its original new key across fresh journal instances',async()=>{const d=deps();d.prepare.mockRejectedValue(new Error('lost'));await expect(live.renewLiveCopyConsent(current,original(),d)).rejects.toThrow('lost');const resumed=deps();const result=await live.renewLiveCopyConsent(current,original(),resumed);expect(result.mandate.id).toBe('successor');expect(resumed.findMandate).toHaveBeenCalledWith('successor_key_123456789');expect(resumed.newKey).not.toHaveBeenCalled();expect(resumed.prepare).not.toHaveBeenCalled();expect(resumed.sign).not.toHaveBeenCalled();});
it.each(['missing','ineligible','localOnlyExpired','stale','future','wrongNonce','wrongRevision','stopped'] as const)('denies %s renewal evidence with zero new key or POST',async kind=>{const d=deps(),review=original();if(kind==='missing')Reflect.deleteProperty(review,'renewal');if(kind==='ineligible'||kind==='localOnlyExpired')review.renewal={...review.renewal,eligible:false,reason:null};if(kind==='stale')review.renewal.checkedAt=new Date(clock-5001).toISOString();if(kind==='future')review.renewal.checkedAt=new Date(clock+1).toISOString();if(kind==='wrongNonce')review.renewal.nonce++;if(kind==='wrongRevision')review.renewal.revision++;if(kind==='stopped')Reflect.set(review.mandate,'state','stopped');await expect(live.renewLiveCopyConsent(current,review,d)).rejects.toThrow();expect(d.newKey).not.toHaveBeenCalled();expect(d.prepare).not.toHaveBeenCalled();});
it.each(['owner','account','strategy','setup','grant','original','clock'] as const)('rejects %s change during original GET before new key',async kind=>{const d=deps();d.challenge.mockImplementation(async()=>{const reply=original();if(kind==='owner')owner.session='successor';if(kind==='account')current.account.updatedAt=new Date(clock+1).toISOString();if(kind==='strategy')current.strategy.version++;if(kind==='setup')current.setup.state='revoked';if(kind==='grant')current.grant!.version=2;if(kind==='original')current.mandate.revision++;if(kind==='clock')clock--;return reply;});await expect(live.renewLiveCopyConsent(current,original(),d)).rejects.toThrow();expect(d.newKey).not.toHaveBeenCalled();expect(d.prepare).not.toHaveBeenCalled();});
it.each(['expiredAgent','revokedGrant','noGrant','mainnetSource','adoption'] as const)('blocks %s without silently changing saved settings',async kind=>{const d=deps();if(kind==='expiredAgent')current.setup.expiresAt=new Date(clock).toISOString();if(kind==='revokedGrant')current.grant!.revokedAt=new Date(clock).toISOString();if(kind==='noGrant')delete current.grant;if(kind==='mainnetSource')current.strategy.sourceNetwork='mainnet';if(kind==='adoption')current.strategy.settings.copyStartMode='adopt';const captured=structuredClone(current);await expect(live.renewLiveCopyConsent(current,original(),d)).rejects.toThrow();expect(current).toEqual(captured);expect(d.newKey).not.toHaveBeenCalled();expect(d.prepare).not.toHaveBeenCalled();});
it('rechecks proof freshness and exact binding after token wait at the actual POST guard',async()=>{const d=deps(),http=vi.fn();d.prepare.mockImplementation(async(_id,_body,guard)=>{clock+=5001;guard();http();return successor();});await expect(live.renewLiveCopyConsent(current,original(),d)).rejects.toThrow();expect(http).not.toHaveBeenCalled();expect(journal().read().renewals).toHaveLength(1);expect(journal().read().renewals[0].mandateId).toBeNull();});
it.each(['sameId','nonIncreasingNonce','foreignAccount','foreignAuthorization'] as const)('rejects %s successor instead of treating original terms as a new review',async kind=>{const d=deps();d.prepare.mockImplementation(async()=>{const reply=successor();if(kind==='sameId'){reply.mandate.id=liveMandate.id;reply.intent.mandateId=liveMandate.id;}if(kind==='nonIncreasingNonce')reply.intent.nonce=liveNow;if(kind==='foreignAccount')reply.intent.accountAddress=`0x${'77'.repeat(20)}`;if(kind==='foreignAuthorization')reply.intent.authorizationId='foreign';return reply;});await expect(live.renewLiveCopyConsent(current,original(),d)).rejects.toThrow();expect(journal().read().renewals[0].mandateId).toBeNull();expect(d.sign).not.toHaveBeenCalled();});
it('storage failure blocks POST, preserving prior unknown markers',async()=>{const d=deps();d.journal=live.createLiveCopyJournal('blocked',{getItem:()=>null,setItem(){throw Error('blocked');}});await expect(live.renewLiveCopyConsent(current,original(),d)).rejects.toThrow('blocked');expect(d.prepare).not.toHaveBeenCalled();});
it('uses the explicitly captured current settings for a separate successor review, preserving original terms',async()=>{const {createHash}=await import('node:crypto');const old=original();current.strategy={...current.strategy,version:2,settings:{...current.strategy.settings,maxLeverage:5}};const d=deps();d.prepare.mockImplementation(async()=>{const reply=successor();reply.mandate.strategyVersion=2;reply.intent.strategyVersion=2;reply.intent.settingsDigest=createHash('sha256').update(JSON.stringify(current.strategy.settings)).digest('hex');return reply;});const result=await live.renewLiveCopyConsent(current,old,d);expect(result.intent.strategyVersion).toBe(2);expect(result.intent.settingsDigest).not.toBe(old.intent.settingsDigest);expect(old.intent).toEqual(liveIntent);expect(d.sign).not.toHaveBeenCalled();});

it('a full append-only generation journal rejects a new request without truncating stored keys',async()=>{const d=deps();await live.renewLiveCopyConsent(current,original(),d);const base=d.journal.read().renewals[0];const generations=Array.from({length:100},(_,i)=>({...base,key:`history_key_${String(i).padStart(16,'0')}`,predecessor:{...base.predecessor,id:`old_${i}`},evidence:{...base.evidence,mandateId:`old_${i}`}}));memory.set(`copy-live-renewals:v1:${encodeURIComponent('renewal-owner')}`,JSON.stringify({generations}));const before=[...memory.entries()],next=deps();await expect(live.renewLiveCopyConsent(current,original(),next)).rejects.toThrow();expect(next.prepare).not.toHaveBeenCalled();expect([...memory.entries()]).toEqual(before);});
it('corrupt generation storage fails closed instead of silently resetting history',async()=>{memory.set(`copy-live-renewals:v1:${encodeURIComponent('renewal-owner')}`,'{"generations":[{"key":"broken"}]}');const d=deps();await expect(live.renewLiveCopyConsent(current,original(),d)).rejects.toThrow();expect(d.newKey).not.toHaveBeenCalled();expect(d.prepare).not.toHaveBeenCalled();});
it('known revoked originals can prepare against an explicitly current replacement agent for a new review',async()=>{const review=original();review.mandate={...review.mandate,state:'revoked',revision:2};review.renewal={...review.renewal,revision:2,reason:'revoked'};current.mandate=review.mandate;current.setup={...current.setup,id:'replacement',agentAddress:`0x${'55'.repeat(20)}`,authorizationId:'replacement-grant'};current.grant={...current.grant!,id:'replacement-grant',signerAddress:current.setup.agentAddress!};const d=deps();d.challenge.mockResolvedValue(review);d.prepare.mockImplementation(async()=>{const reply=successor();reply.intent={...reply.intent,setupId:'replacement',agentAddress:current.setup.agentAddress!,authorizationId:'replacement-grant'};return reply;});const result=await live.renewLiveCopyConsent(current,review,d);expect(result.intent.agentAddress).not.toBe(review.intent.agentAddress);expect(d.sign).not.toHaveBeenCalled();});
it('the real token await cannot carry an aged renewal proof into HTTP',async()=>{const {api,setAccessTokenGetter}=await import('@/lib/api');const fetch=vi.fn();vi.stubGlobal('fetch',fetch);let finish!:(token:string)=>void;setAccessTokenGetter(()=>new Promise(r=>{finish=r;}),'renew-owner');try{const d=deps();d.prepare.mockImplementation((id,body,beforeSend)=>api.post(`/me/copy/live/execution-wallets/${id}/mandates`,body,{beforeSend}));const pending=live.renewLiveCopyConsent(current,original(),d),rejected=expect(pending).rejects.toThrow();for(let i=0;!finish&&i<50;i++)await new Promise(r=>setTimeout(r,1));expect(finish).toBeTypeOf('function');clock+=5001;finish('public-test-token');await rejected;expect(fetch).not.toHaveBeenCalled();expect(d.journal.read().renewals[0].mandateId).toBeNull();}finally{setAccessTokenGetter(null,null);vi.unstubAllGlobals();}});
