// @vitest-environment happy-dom
import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { CopyAccountModeSettings } from "@/components/settings/copy-account-mode";
import { I18nProvider } from "@/i18n/provider";
import { catalogs } from "@/i18n/messages";
import { LOCALES, type Locale } from "@/i18n/config";
import type { CopyAccountModeOperation, CopyExecutionAccount } from "@trading-dashboard/shared/contracts";
import { settleQueries, type SettleOptions } from "./query-settle";
const state = vi.hoisted(() => ({ get: vi.fn(), post: vi.fn(), sign: vi.fn(), identity: "owner", session: "1", status: "signedIn", mode: "privy", walletAddress: `0x${"11".repeat(20)}` as string | null }));
vi.mock("@/lib/auth", () => ({ useAuth: () => ({ status: state.status, mode: state.mode, identity: state.identity, wallet: state.walletAddress ? { address: state.walletAddress, signTypedData: state.sign } : null }) }));
vi.mock("@/lib/api", () => ({ api: { get: state.get, post: state.post }, sessionKey: () => state.session }));
vi.mock("next/navigation", () => ({ useRouter: () => ({ refresh() {} }) }));
const account: CopyExecutionAccount = { id: "account", strategyId: 9, network: "testnet", state: "ready", address: `0x${"22".repeat(20)}`, issue: null, createdAt: "2026-10-04T00:00:00Z", updatedAt: "2026-10-04T00:00:00Z" };
const op: CopyAccountModeOperation = { id: "operation", accountId: account.id, strategyId: 9, network: "testnet", accountAddress: account.address!, target: "disabled", revision: 1, submissionState: "prepared", targetState: "unproven", issue: null, observedAt: null, attemptedAt: null, createdAt: account.createdAt, updatedAt: account.updatedAt };
let root: Root, container: HTMLDivElement, client: QueryClient, data: { available: boolean; network: "testnet"; operations: CopyAccountModeOperation[] };
beforeEach(() => { Object.assign(globalThis, { IS_REACT_ACT_ENVIRONMENT: true }); window.sessionStorage.clear(); Object.assign(state, { identity: "owner", session: "1", status: "signedIn", mode: "privy", walletAddress: `0x${"11".repeat(20)}` }); state.get.mockReset(); state.post.mockReset(); state.sign.mockReset().mockResolvedValue(`0x${"aa".repeat(65)}`); data = { available: true, network: "testnet", operations: [] }; state.get.mockImplementation(async () => data); client = new QueryClient({ defaultOptions: { queries: { retry: false } } }); container = document.createElement("div"); document.body.append(container); root = createRoot(container); });
afterEach(async () => { await act(async () => root.unmount()); client.clear(); container.remove(); vi.useRealTimers(); });
// Waits for the mode queries and mutations to answer (advancing fake timers when on);
// settleHeld() waits for queries only, while a test holds the challenge or wallet prompt open.
const settle = (options?: SettleOptions) => settleQueries(client, { ms: 20, ...options });
const settleHeld = () => settle({ mutations: false });
async function render(accounts: readonly CopyExecutionAccount[] = [account], locale: Locale = "en", wait: () => Promise<void> = settle) { await act(async () => root.render(<QueryClientProvider client={client}><I18nProvider locale={locale} messages={catalogs[locale]}><CopyAccountModeSettings accounts={accounts}/></I18nProvider></QueryClientProvider>)); await wait(); }
function button(label: string) { const item = [...container.querySelectorAll("button")].find(b => b.textContent === label); if (!item) throw new Error(`Missing button ${label}`); return item; }
async function click(label: string, wait: () => Promise<void> = settle) { await act(async () => button(label).click()); await wait(); }
async function select(id = account.id) { await act(async () => { const item = container.querySelector("select")!; item.value = id; item.dispatchEvent(new Event("change", { bubbles: true })); }); await settle(); }
async function review() { await act(async () => (container.querySelector('input[type="checkbox"]') as HTMLInputElement).click()); await settle(); }
function challenge(operation = op) { const nonce = Date.now(); return { operation, intent: { operationId: op.id, accountId: op.accountId, strategyId: op.strategyId, network: op.network, accountAddress: op.accountAddress, nonce, consentExpiresAt: nonce + 300000 } }; }
it("requires separate explicit preparation and owner review, and separates accepted from supported", async () => { await render(); expect(state.post).not.toHaveBeenCalled(); await select(); state.post.mockImplementation(async (path) => { if (path.endsWith('/mode')) { data.operations = [op]; return op; } if (path.endsWith('/challenge')) return challenge({ ...op, revision: 2 }); data.operations = [{ ...op, revision: 3, submissionState: "accepted" }]; return data.operations[0]; }); await click("Prepare account mode"); expect(state.sign).not.toHaveBeenCalled(); expect(button("Confirm and sign mode consent").disabled).toBe(true); expect(container.textContent).toContain(account.address); expect(container.textContent).toContain(state.walletAddress); expect(container.textContent).toContain("or start copying"); await review(); await click("Confirm and sign mode consent"); expect(state.sign).toHaveBeenCalledOnce(); expect(state.sign.mock.calls[0][0].message).toMatchObject({ account: account.address, abstraction: "disabled", network: "testnet" }); expect(container.textContent).toContain("Submission accepted"); expect(container.textContent).toContain("Mode remains unproven"); expect(container.querySelector('input[type="checkbox"]')).toBeNull(); });
it.each(["signing", "unknown", "accepted", "rejected"] as const)("%s allows only checking the original operation", async (submissionState) => { data.operations = [{ ...op, submissionState }]; state.post.mockResolvedValue(data.operations[0]); await render(); await select(); expect(container.querySelector('input[type="checkbox"]')).toBeNull(); expect(state.post).not.toHaveBeenCalled(); await click("Check original mode operation"); expect(state.post.mock.calls.map(([p]) => p)).toEqual(["/me/copy/account-modes/operation/reconcile"]); expect(state.sign).not.toHaveBeenCalled(); });
it.each(["supported", "unsupported"] as const)("prepared %s never signs or prepares a replacement", async (targetState) => { data.operations = [{ ...op, targetState }]; await render(); await select(); expect(container.querySelector('input[type="checkbox"]')).toBeNull(); expect(container.textContent).not.toContain("Confirm and sign mode consent"); expect(state.post).not.toHaveBeenCalled(); });
it("recovers a lost preparation with a GET by the original key across remount, never a POST retry", async () => { state.post.mockRejectedValue(new Error("secret diagnostic")); await render(); await select(); await click("Prepare account mode"); const key = state.post.mock.calls[0][1].idempotencyKey; expect(container.textContent).not.toContain("secret diagnostic"); await act(async () => root.unmount()); client.clear(); root = createRoot(container); await render(); await select(); expect(state.post).toHaveBeenCalledTimes(1); state.get.mockImplementation(async (path) => path.includes('/by-key/') ? op : data); await click("Find original preparation"); expect(state.get).toHaveBeenCalledWith(`/me/copy/account-modes/by-key/${key}`); expect(state.post).toHaveBeenCalledTimes(1); expect(state.sign).not.toHaveBeenCalled(); expect(button("Prepare account mode").disabled).toBe(true); });
it("persists uncertain approval across remount and never requests a new challenge", async () => { data.operations = [op]; state.post.mockImplementation(async path => { if (path.endsWith('/challenge')) return challenge(); throw new Error("lost"); }); await render(); await select(); await review(); await click("Confirm and sign mode consent"); await act(async () => root.unmount()); client.clear(); root = createRoot(container); await render(); await select(); expect(container.querySelector('input[type="checkbox"]')).toBeNull(); state.post.mockResolvedValue({ ...op, submissionState: "unknown", revision: 2 }); await click("Check original mode operation"); expect(state.sign).toHaveBeenCalledOnce(); expect(state.post.mock.calls.filter(([p]) => p.endsWith('/challenge'))).toHaveLength(1); });
const changes = (['challenge', 'signature'] as const).flatMap(gate => (["revision", "state", "address", "account", "session"] as const).map(change => ({ gate, change })));
it.each(changes)("blocks held $gate after $change changes", async ({ gate, change }) => { data.operations = [op]; let finish!: (value: unknown) => void; state.post.mockImplementation(path => path.endsWith('/challenge') ? gate === "challenge" ? new Promise(resolve => { finish = resolve; }) : Promise.resolve(challenge()) : Promise.resolve({ ...op, submissionState: "accepted", revision: 2 })); if (gate === "signature") state.sign.mockImplementation(() => new Promise(resolve => { finish = resolve; })); await render(); await select(); await review(); await click("Confirm and sign mode consent", settleHeld); let accounts = [account]; if (change === 'revision') data.operations = [{ ...op, revision: 2 }]; if (change === 'state') data.operations = [{ ...op, submissionState: "unknown" }]; if (change === 'address') data.operations = [{ ...op, accountAddress: `0x${"44".repeat(20)}` }]; if (change === 'account') accounts = [{ ...account, state: "blocked" }]; if (change === 'session') { state.session = '2'; state.identity = 'other'; data.operations = []; } await render(accounts, "en", settleHeld); await act(async () => { await client.invalidateQueries(); }); await settleHeld(); await act(async () => finish(gate === "challenge" ? challenge() : `0x${"aa".repeat(65)}`)); await settle(); expect(state.post.mock.calls.filter(([p]) => p.endsWith('/approve'))).toHaveLength(0); expect(state.sign).toHaveBeenCalledTimes(gate === "challenge" ? 0 : 1); });
it("does not send expired consent after a held wallet prompt", async () => { vi.useFakeTimers(); vi.setSystemTime(new Date('2026-10-04T00:00:00Z')); data.operations = [op]; state.post.mockResolvedValue(challenge()); let finish!: (signature: string) => void; state.sign.mockImplementation(() => new Promise(resolve => { finish = resolve; })); await render(); await select(); await review(); await click("Confirm and sign mode consent", settleHeld); vi.setSystemTime(new Date(Date.now() + 300001)); await act(async () => window.dispatchEvent(new Event('focus'))); await act(async () => finish(`0x${"aa".repeat(65)}`)); await settle(); expect(state.post.mock.calls.filter(([p]) => p.endsWith('/approve'))).toHaveLength(0); expect(container.textContent).toContain("Consent expired"); });
it.each(LOCALES)("provides translated labels and conservative mode terms in %s", async locale => { data.operations = [{ ...op, submissionState: 'accepted', targetState: 'unproven' }]; await render([account], locale); await select(); const messages = catalogs[locale].copyAccountMode; expect(container.querySelector('section')?.getAttribute('aria-label')).toBe(messages.title); expect(container.textContent).toContain(messages.submissionStates.accepted); expect(container.textContent).toContain(messages.targetStates.unproven); expect(container.textContent).toContain(messages.hint); expect(state.post).not.toHaveBeenCalled(); });
it.each([{ state: "blocked" as const }, { network: "mainnet" as const }])("rejects unavailable accounts %j", async change => { await render([{ ...account, ...change }]); expect(container.querySelector('select option[value="account"]')).toBeNull(); expect(state.post).not.toHaveBeenCalled(); });
it("checking a prepared operation never invokes consent or wallet signing without review", async () => { data.operations = [op]; state.post.mockResolvedValue(op); await render(); await select(); await click("Check original mode operation"); expect(state.post.mock.calls.map(([p]) => p)).toEqual(["/me/copy/account-modes/operation/reconcile"]); expect(state.sign).not.toHaveBeenCalled(); });
it("clears former account details immediately when selecting another account", async () => { data.operations = [op]; const other = { ...account, id: "other", strategyId: 10, address: `0x${"44".repeat(20)}` }; await render([account, other]); await select(); expect(container.textContent).toContain(account.address); await select(other.id); expect(container.textContent).not.toContain(account.address); expect(container.textContent).not.toContain("Mode remains unproven"); expect(container.textContent).toContain(other.address); expect(state.post).not.toHaveBeenCalled(); });
it("fails closed when a background overview fails instead of showing old success controls", async () => { data.operations = [op]; await render(); await select(); await review(); state.get.mockRejectedValue(new Error("private detail")); await act(async () => { await client.invalidateQueries(); }); await settle(); expect(container.querySelector('input[type="checkbox"]')).toBeNull(); expect(button("Prepare account mode").disabled).toBe(true); expect(container.textContent).not.toContain("private detail"); expect(state.post).not.toHaveBeenCalled(); });
it("requires renewed review after an observed operation revision changes", async () => { data.operations = [op]; await render(); await select(); await review(); expect(button("Confirm and sign mode consent").disabled).toBe(false); data.operations = [{ ...op, revision: 2 }]; await act(async () => { await client.invalidateQueries(); }); await settle(); expect(button("Confirm and sign mode consent").disabled).toBe(true); expect((container.querySelector('input[type="checkbox"]') as HTMLInputElement).checked).toBe(false); });
it("does not expose raw provider issues in a rejected operation", async () => { data.operations = [{ ...op, submissionState: "rejected", issue: "private-provider-token-detail" }]; await render(); await select(); expect(container.textContent).not.toContain("private-provider-token-detail"); expect(container.textContent).toContain(catalogs.en.copyAccountMode.error); });
it("expires an idle prepared challenge locally after a cancelled wallet prompt", async () => { vi.useFakeTimers(); vi.setSystemTime(new Date('2026-10-04T00:00:00Z')); data.operations = [op]; const proof = challenge(); proof.intent.consentExpiresAt = Date.now() + 2000; state.post.mockResolvedValue(proof); state.sign.mockRejectedValue(new Error('cancelled')); await render(); await select(); await review(); await click("Confirm and sign mode consent"); const reads = state.get.mock.calls.length; await act(async () => { await vi.advanceTimersByTimeAsync(2100); }); expect(container.textContent).toContain("Consent expired"); expect(container.querySelector('input[type="checkbox"]')).toBeNull(); expect(state.get).toHaveBeenCalledTimes(reads); expect(state.post.mock.calls.filter(([p]) => p.endsWith('/approve'))).toHaveLength(0); });
it("retains the original uncertainty barrier when the same owner's signing wallet changes", async () => { data.operations = [op]; state.post.mockImplementation(async path => path.endsWith('/challenge') ? challenge() : Promise.reject(new Error('lost'))); await render(); await select(); await review(); await click("Confirm and sign mode consent"); state.walletAddress = `0x${"44".repeat(20)}`; await render(); await select(); expect(container.querySelector('input[type="checkbox"]')).toBeNull(); state.post.mockResolvedValue({ ...op, submissionState: 'unknown', revision: 2 }); await click("Check original mode operation"); expect(state.sign).toHaveBeenCalledOnce(); expect(state.post.mock.calls.filter(([p]) => p.endsWith('/challenge'))).toHaveLength(1); });
