import { beforeEach, expect, it, vi } from 'vitest';
import { createLiveCopyJournal, createLiveCopyDraft, prepareLiveCopyConsent, approveLiveCopyConsent } from '@/lib/copy-live';
import { liveCopyMandateOwnerTypedData } from '@trading-dashboard/shared/contracts';
import { liveContext, liveIntent, liveMandate, liveNow, liveOwner, liveSettings, liveStrategy } from './copy-live-fixtures';
let owner: { status: string; mode: string; identity: string | null; session: string; walletAddress: string | null }, memory: Map<string, string>, current: ReturnType<typeof liveContext>, clock: number;
beforeEach(() => { owner = { status: 'signedIn', mode: 'privy', identity: 'owner@email', session: '1', walletAddress: liveOwner }; memory = new Map(); current = liveContext(); clock = liveNow; });
function deps() { return { snapshot: () => ({ ...owner }), current: () => current, now: () => clock, newKey: () => 'original_key_123456789', journal: createLiveCopyJournal('scope', { getItem: (key: string) => memory.get(key) ?? null, setItem: (key: string, value: string) => { memory.set(key, value); } }),
  create: vi.fn().mockResolvedValue(liveStrategy), findStrategy: vi.fn().mockResolvedValue(liveStrategy), prepare: vi.fn().mockResolvedValue({ mandate: liveMandate, intent: liveIntent }), findMandate: vi.fn().mockResolvedValue({ mandate: liveMandate, intent: liveIntent }), challenge: vi.fn().mockResolvedValue({ mandate: liveMandate, intent: liveIntent }), sign: vi.fn().mockResolvedValue(`0x${'aa'.repeat(65)}`), approve: vi.fn().mockResolvedValue({ ...liveMandate, state: 'active', revision: 2 }) }; }
const draft = () => ({ leader: liveStrategy.leaderAddress, sourceNetwork: 'testnet' as const, budgetUsd: '100', settings: liveSettings });
it('persists exact paused draft request before POST and never allocates paper or signs', async () => { const d = deps(); d.create.mockImplementation(async () => { expect([...memory.values()].join()).toContain('original_key_123456789'); return liveStrategy; }); expect(await createLiveCopyDraft(draft(), d)).toEqual(liveStrategy); expect(d.sign).not.toHaveBeenCalled(); expect(d.create).toHaveBeenCalledOnce(); });
it('lost draft response can only read the original key, never send or generate another request', async () => { const d = deps(); d.create.mockRejectedValue(new Error('lost')); await expect(createLiveCopyDraft(draft(), d)).rejects.toThrow('lost'); const resumed = deps(); expect(await createLiveCopyDraft(draft(), resumed)).toEqual(liveStrategy); expect(resumed.findStrategy).toHaveBeenCalledWith('original_key_123456789'); expect(resumed.create).not.toHaveBeenCalled(); });
it('does not replace an uncertain request with changed budget or leader', async () => { const d = deps(); d.create.mockRejectedValue(new Error('lost')); await expect(createLiveCopyDraft(draft(), d)).rejects.toThrow(); await expect(createLiveCopyDraft({ ...draft(), budgetUsd: '101' }, d)).rejects.toThrow(); expect(d.create).toHaveBeenCalledOnce(); });
it('requires durable storage before any mutation', async () => { const d = deps(); d.journal = createLiveCopyJournal('scope', { getItem: () => null, setItem() { throw new Error('blocked'); } }); await expect(createLiveCopyDraft(draft(), d)).rejects.toThrow('blocked'); expect(d.create).not.toHaveBeenCalled(); });
it('prepares exact consent without a wallet signature and reads original preparation after uncertainty', async () => { const d = deps(); d.prepare.mockRejectedValue(new Error('lost')); await expect(prepareLiveCopyConsent(current, d)).rejects.toThrow('lost'); const resumed = deps(); await prepareLiveCopyConsent(current, resumed); expect(resumed.findMandate).toHaveBeenCalledWith('original_key_123456789'); expect(resumed.prepare).not.toHaveBeenCalled(); expect(resumed.sign).not.toHaveBeenCalled(); });
it('signs the exact local mandate and persists uncertainty before approve, without storing signature', async () => { const d = deps(); d.approve.mockImplementation(async () => { expect(d.journal.read().approvals).toContain(liveMandate.id); return { ...liveMandate, state: 'active', revision: 2 }; }); const result = await approveLiveCopyConsent(current, d); expect(result.state).toBe('active'); expect(d.sign).toHaveBeenCalledExactlyOnceWith(liveCopyMandateOwnerTypedData(liveIntent)); expect(d.approve).toHaveBeenCalledWith(liveMandate.id, { consentSignature: `0x${'aa'.repeat(65)}` }, expect.any(Function)); expect([...memory.values()].join()).not.toContain('aa'.repeat(65)); });
it('unknown approval and nonprepared mandates are original GET-only with no signature or POST', async () => { const d = deps(); d.approve.mockRejectedValue(new Error('lost')); await expect(approveLiveCopyConsent(current, d)).rejects.toThrow('lost'); const resumed = deps(); await approveLiveCopyConsent(current, resumed); expect(resumed.challenge).toHaveBeenCalledOnce(); expect(resumed.sign).not.toHaveBeenCalled(); expect(resumed.approve).not.toHaveBeenCalled(); current.mandate.state = 'active'; const active = deps(); await approveLiveCopyConsent(current, active); expect(active.sign).not.toHaveBeenCalled(); });
it.each(['identity', 'session', 'walletAddress', 'mode', 'status'] as const)('rejects %s change during wallet prompt with zero POST', async field => { const d = deps(); d.sign.mockImplementation(async () => { owner = { ...owner, [field]: 'changed' }; return `0x${'aa'.repeat(65)}`; }); await expect(approveLiveCopyConsent(current, d)).rejects.toThrow(); expect(d.approve).not.toHaveBeenCalled(); });
it.each(['account', 'strategy', 'setup', 'mandate'] as const)('rejects current %s changes during challenge and wallet prompt', async field => { const edit = () => { if (field === 'account') current.account.updatedAt = new Date(liveNow + 1).toISOString(); if (field === 'strategy') current.strategy.version++; if (field === 'setup') current.setup.state = 'revoked'; if (field === 'mandate') current.mandate.revision++; }; const d = deps(); d.challenge.mockImplementation(async () => { edit(); return { mandate: liveMandate, intent: liveIntent }; }); await expect(approveLiveCopyConsent(current, d)).rejects.toThrow(); expect(d.sign).not.toHaveBeenCalled(); current = liveContext(); const s = deps(); s.sign.mockImplementation(async () => { edit(); return `0x${'aa'.repeat(65)}`; }); await expect(approveLiveCopyConsent(current, s)).rejects.toThrow(); expect(s.approve).not.toHaveBeenCalled(); });
it('rejects expiry inside wallet prompt and at actual final POST guard after token wait', async () => { const d = deps(); d.sign.mockImplementation(async () => { clock += 300000; return `0x${'aa'.repeat(65)}`; }); await expect(approveLiveCopyConsent(current, d)).rejects.toThrow(); expect(d.approve).not.toHaveBeenCalled(); clock = liveNow; const s = deps(), http = vi.fn(); s.approve.mockImplementation(async (_id: string, _body: unknown, guard: () => void) => { clock += 300000; guard(); http(); return liveMandate; }); await expect(approveLiveCopyConsent(current, s)).rejects.toThrow(); expect(http).not.toHaveBeenCalled(); });
it.each(['strategyVersion', 'accountAddress', 'ownerAddress', 'agentAddress', 'authorizationId', 'settingsDigest', 'budgetUsd', 'mandateId'] as const)('rejects substituted %s before wallet prompt', async field => { const d = deps(); d.challenge.mockResolvedValue({ mandate: liveMandate, intent: { ...liveIntent, [field]: field === 'strategyVersion' ? 2 : field === 'settingsDigest' ? 'b'.repeat(64) : 'changed' } }); await expect(approveLiveCopyConsent(current, d)).rejects.toThrow(); expect(d.sign).not.toHaveBeenCalled(); });
it('checks exact account/strategy at the create and prepare POST boundary', async () => { const d = deps(), http = vi.fn(); d.prepare.mockImplementation(async (_id: string, _body: unknown, guard: () => void) => { current.account.state = 'blocked'; guard(); http(); return { mandate: liveMandate, intent: liveIntent }; }); await expect(prepareLiveCopyConsent(current, d)).rejects.toThrow(); expect(http).not.toHaveBeenCalled(); });
it('rejects a valid but different original signed intent than the one explicitly reviewed', async () => { const d = deps(); clock = liveNow + 10; d.challenge.mockResolvedValue({ mandate: liveMandate, intent: { ...liveIntent, nonce: liveNow + 1 } }); await expect(approveLiveCopyConsent({ ...current, reviewedIntent: liveIntent }, d)).rejects.toThrow(); expect(d.sign).not.toHaveBeenCalled(); });
it('checks optional public account/setup revision against exact intent without inventing missing revisions', async () => { const d = deps(); Reflect.set(current.account, 'revision', 2); await expect(approveLiveCopyConsent(current, d)).rejects.toThrow(); expect(d.sign).not.toHaveBeenCalled(); current = liveContext(); Reflect.set(current.setup, 'revision', 2); await expect(approveLiveCopyConsent(current, d)).rejects.toThrow(); expect(d.sign).not.toHaveBeenCalled(); });
it.each(['account', 'strategy', 'setup', 'mandate', 'expiry'] as const)('rechecks %s after the real API token await and before HTTP', async kind => {
  const { api, setAccessTokenGetter } = await import('@/lib/api'); const fetch = vi.fn(); vi.stubGlobal('fetch', fetch); let release!: (v: string) => void; setAccessTokenGetter(() => new Promise(r => { release = r; }), 'live-owner');
  const d = deps(); d.approve.mockImplementation((id: string, body: { consentSignature: string }, beforeSend: () => void) => api.post(`/me/copy/live/mandates/${id}/approve`, body, { beforeSend }));
  const original = approveLiveCopyConsent(current, d); const rejected = expect(original).rejects.toThrow();
  for (let i = 0; !release && i < 50; i++) await new Promise(r => setTimeout(r, 1)); expect(release).toBeTypeOf('function');
  if (kind === 'account') current.account.updatedAt = new Date(liveNow + 1).toISOString(); if (kind === 'strategy') current.strategy.version++; if (kind === 'setup') current.setup.state = 'revoked'; if (kind === 'mandate') current.mandate.revision++; if (kind === 'expiry') clock += 300000;
  release('public-test-token'); await rejected; expect(fetch).not.toHaveBeenCalled(); setAccessTokenGetter(null, null); vi.unstubAllGlobals();
});
it('actual wallet preparation persists original strategy before POST and only reads after loss', async () => {
  const { prepareActualCopyWallet } = await import('@/lib/copy-live'); const d = deps(), createWallet = vi.fn().mockRejectedValue(new Error('lost')), readWallets = vi.fn().mockResolvedValue({ available: true, network: 'testnet', accounts: [current.account], authorizations: [] });
  const w = { ...d, currentStrategy: () => current.strategy, createWallet, readWallets };
  await expect(prepareActualCopyWallet(current.strategy, w)).rejects.toThrow('lost'); const result = await prepareActualCopyWallet(current.strategy, w); expect(result).toEqual(current.account); expect(createWallet).toHaveBeenCalledOnce(); expect(readWallets).toHaveBeenCalledOnce(); expect(d.sign).not.toHaveBeenCalled();
});
it('actual wallet preparation final token boundary refuses a changed strategy version with no HTTP', async () => {
  const { prepareActualCopyWallet } = await import('@/lib/copy-live'); const d = deps(), http = vi.fn(); const createWallet = vi.fn(async (_id: number, _body: unknown, guard: () => void) => { current.strategy.version++; guard(); http(); return current.account; });
  await expect(prepareActualCopyWallet(current.strategy, { ...d, currentStrategy: () => current.strategy, createWallet, readWallets: vi.fn() })).rejects.toThrow(); expect(http).not.toHaveBeenCalled();
});
it('checks actual public authorization version when that grant is present', async () => { const d = deps(); Reflect.set(current, 'grant', { id: 'grant', strategyId: current.strategy.id, network: 'testnet', accountAddress: current.account.address, signerAddress: current.setup.agentAddress, status: 'active', scopes: ['copy:trade', 'copy:reduce'], expiresAt: current.setup.expiresAt, revokedAt: null, version: 2 }); await expect(approveLiveCopyConsent(current, d)).rejects.toThrow(); expect(d.sign).not.toHaveBeenCalled(); });
