import { beforeEach, expect, it, vi } from "vitest";
import { accountModeOwnerConsentTypedData, userSetAbstractionTypedData, WALLET_NETWORKS, type CopyAccountModeOperation, type CopyExecutionAccount } from "@trading-dashboard/shared/contracts";
import { createAccountModeJournal, prepareCopyAccountMode, runCopyAccountModeConsent } from "@/lib/copy-account-modes";

const now = Date.parse("2026-10-04T00:00:00Z");
const account: CopyExecutionAccount = { id: "account", strategyId: 9, network: "testnet", state: "ready", address: `0x${"22".repeat(20)}`, issue: null, createdAt: new Date(now).toISOString(), updatedAt: new Date(now).toISOString() };
const op: CopyAccountModeOperation = { id: "mode", accountId: account.id, strategyId: 9, network: "testnet", accountAddress: account.address!, target: "disabled", revision: 1, submissionState: "prepared", targetState: "unproven", issue: null, observedAt: null, attemptedAt: null, createdAt: account.createdAt, updatedAt: account.updatedAt };
const intent = { operationId: op.id, accountId: op.accountId, strategyId: op.strategyId, network: op.network, accountAddress: op.accountAddress, nonce: now, consentExpiresAt: now + 300000 };
/** The server's prepared action: the copy account's exact mode change. */
const masterAction = { kind: "account_mode" as const, account: op.accountAddress, typedData: userSetAbstractionTypedData(WALLET_NETWORKS.testnet, op.accountAddress, now), digest: `0x${"ab".repeat(32)}`, expiresAt: now + 300000 };
const masterSignature = `0x${"bb".repeat(65)}`;
let memory: Map<string, string>, owner: { status: string; mode: string; identity: string | null; session: string; walletAddress: string | null };
function deps() { return { snapshot: () => ({ ...owner }), now: () => now, journal: createAccountModeJournal("owner", { getItem: (k) => memory.get(k) ?? null, setItem: (k, v) => { memory.set(k, v); } }), assertCurrent: vi.fn(), newKey: () => "original-key-0001", create: vi.fn().mockResolvedValue(op), sign: vi.fn().mockResolvedValue(`0x${"aa".repeat(65)}`), signAccount: vi.fn().mockResolvedValue(masterSignature), challenge: vi.fn().mockResolvedValue({ operation: op, intent, masterAction }), approve: vi.fn().mockResolvedValue({ ...op, submissionState: "accepted", revision: 2 }), reconcile: vi.fn().mockResolvedValue({ ...op, submissionState: "unknown", revision: 2 }) }; }
beforeEach(() => { memory = new Map(); owner = { status: "signedIn", mode: "privy", identity: "owner", session: "1", walletAddress: `0x${"11".repeat(20)}` }; });
it("persists preparation identity before its only POST, without signing", async () => { const d = deps(); d.create.mockImplementation(async () => { expect([...memory.values()].join()).toContain("original-key-0001"); return op; }); expect(await prepareCopyAccountMode(account, d)).toEqual(op); expect(d.create).toHaveBeenCalledExactlyOnceWith(account.id, { idempotencyKey: "original-key-0001" }, expect.any(Function)); expect(d.sign).not.toHaveBeenCalled(); });
it("never resends a lost preparation or invents a replacement key", async () => { const d = deps(); d.create.mockRejectedValueOnce(new Error("lost")); await expect(prepareCopyAccountMode(account, d)).rejects.toThrow("lost"); await expect(prepareCopyAccountMode(account, d)).rejects.toThrow(); expect(d.create).toHaveBeenCalledTimes(1); expect(d.journal.read().creations[0].operationId).toBeNull(); });
it("signs exactly the dedicated testnet master consent and keeps signatures out of recovery", async () => { const d = deps(); expect(await runCopyAccountModeConsent(op, d)).toMatchObject({ submissionState: "accepted", targetState: "unproven" }); expect(d.sign).toHaveBeenCalledExactlyOnceWith(accountModeOwnerConsentTypedData(intent)); expect(d.signAccount).toHaveBeenCalledExactlyOnceWith(op.accountAddress, masterAction.typedData); expect(d.approve).toHaveBeenCalledExactlyOnceWith(op.id, { consentSignature: `0x${"aa".repeat(65)}`, masterSignature }, expect.any(Function)); expect([...memory.values()].join()).not.toContain("aa".repeat(65)); expect([...memory.values()].join()).not.toContain("bb".repeat(65)); });
it.each(["signing", "unknown", "accepted", "rejected"] as const)("only reconciles %s without a signature or new challenge", async (submissionState) => { const d = deps(); await runCopyAccountModeConsent({ ...op, submissionState }, d); expect(d.reconcile).toHaveBeenCalledExactlyOnceWith(op.id, expect.any(Function)); expect(d.sign).not.toHaveBeenCalled(); expect(d.challenge).not.toHaveBeenCalled(); expect(d.approve).not.toHaveBeenCalled(); });
it("durably checks original approval after response loss despite a stale prepared overview", async () => { const d = deps(); d.approve.mockRejectedValueOnce(new Error("lost")); await expect(runCopyAccountModeConsent(op, d)).rejects.toThrow("lost"); const resumed = deps(); await runCopyAccountModeConsent(op, resumed); expect(resumed.reconcile).toHaveBeenCalledExactlyOnceWith(op.id, expect.any(Function)); expect(resumed.sign).not.toHaveBeenCalled(); expect(resumed.challenge).not.toHaveBeenCalled(); });
it.each(["session", "identity", "walletAddress", "mode", "status"] as const)("blocks %s changes while the owner signs", async (field) => { const d = deps(); d.sign.mockImplementation(async () => { owner[field] = "changed"; return `0x${"aa".repeat(65)}`; }); await expect(runCopyAccountModeConsent(op, d)).rejects.toThrow(); expect(d.approve).not.toHaveBeenCalled(); });
it.each(["challenge", "signature"] as const)("blocks a current operation revision/state change during %s", async (gate) => { const d = deps(); let changed = false; d.assertCurrent.mockImplementation(() => { if (changed) throw new Error("mode_operation_changed"); }); if (gate === "challenge") d.challenge.mockImplementation(async () => { changed = true; return { operation: op, intent, masterAction }; }); else d.sign.mockImplementation(async () => { changed = true; return `0x${"aa".repeat(65)}`; }); await expect(runCopyAccountModeConsent(op, d)).rejects.toThrow("mode_operation_changed"); expect(d.approve).not.toHaveBeenCalled(); expect(d.sign).toHaveBeenCalledTimes(gate === "challenge" ? 0 : 1); });
it.each([{ operation: { ...op, id: "wrong" } }, { operation: { ...op, submissionState: "unknown" } }, { intent: { ...intent, accountId: "other" } }, { intent: { ...intent, strategyId: 10 } }, { intent: { ...intent, accountAddress: `0x${"44".repeat(20)}` } }, { intent: { ...intent, network: "mainnet" } }, { intent: { ...intent, consentExpiresAt: now - 1 } }, { intent: { ...intent, nonce: now + 30001, consentExpiresAt: now + 300000 } }])("rejects substituted/expired challenges %j", async (change) => { const d = deps(); d.challenge.mockResolvedValue({ operation: op, intent, masterAction, ...change }); await expect(runCopyAccountModeConsent(op, d)).rejects.toThrow(); expect(d.sign).not.toHaveBeenCalled(); expect(d.approve).not.toHaveBeenCalled(); });
it("never POSTs consent that expired while the wallet prompt was open", async () => { const d = deps(); let clock = now; d.now = () => clock; d.sign.mockImplementation(async () => { clock = intent.consentExpiresAt; return `0x${"aa".repeat(65)}`; }); await expect(runCopyAccountModeConsent(op, d)).rejects.toThrow(); expect(d.approve).not.toHaveBeenCalled(); });
it("fails before preparing or approving when the durable barrier cannot be written", async () => { const d = deps(); d.journal = createAccountModeJournal("owner", { getItem: () => null, setItem: () => { throw new Error("disabled"); } }); await expect(prepareCopyAccountMode(account, d)).rejects.toThrow(); expect(d.create).not.toHaveBeenCalled(); await expect(runCopyAccountModeConsent(op, d)).rejects.toThrow(); expect(d.approve).not.toHaveBeenCalled(); });
it("adopts exactly the reserved challenge revision before all later gates", async () => { const d = deps(), reserved = { ...op, revision: 2 }; d.challenge.mockResolvedValue({ operation: reserved, intent, masterAction }); const adopt = vi.fn(); d.approve.mockResolvedValue({ ...reserved, submissionState: "accepted", revision: 3 }); await runCopyAccountModeConsent(op, { ...d, adoptChallenge: adopt }); expect(adopt).toHaveBeenCalledExactlyOnceWith(op, reserved, intent.consentExpiresAt); expect(d.assertCurrent.mock.calls.at(-2)?.[0].revision).toBe(2); });
it.each(["supported", "unsupported"] as const)("cannot request consent for a prepared %s target", async targetState => { const d = deps(); await runCopyAccountModeConsent({ ...op, targetState }, d); expect(d.challenge).not.toHaveBeenCalled(); expect(d.sign).not.toHaveBeenCalled(); expect(d.reconcile).toHaveBeenCalledOnce(); });
it("rechecks actual consent deadline after token delay at the supplied POST boundary", async () => { const d = deps(); let clock = now; d.now = () => clock; d.approve.mockImplementation(async (_id, _body, beforeSend) => { clock = intent.consentExpiresAt; beforeSend(); return op; }); await expect(runCopyAccountModeConsent(op, d)).rejects.toThrow("mode_consent_expired"); expect(d.journal.uncertain(op.id)).toBe(true); const resumed = deps(); await runCopyAccountModeConsent(op, resumed); expect(resumed.sign).not.toHaveBeenCalled(); });
it("clones the account before an awaiting preparation can mutate its identity", async () => { const d = deps(), original = { ...account }; d.create.mockImplementation(async () => { original.address = `0x${"44".repeat(20)}`; return { ...op, accountAddress: original.address }; }); await expect(prepareCopyAccountMode(original, d)).rejects.toThrow("mode_operation_changed"); expect(d.journal.read().creations[0].address).toBe(account.address); });
it.each([{ account: `0x${"44".repeat(20)}` }, { kind: "usd_send" }, { typedData: userSetAbstractionTypedData(WALLET_NETWORKS.testnet, op.accountAddress, now + 1) }, { expiresAt: now }])(
  "never signs with the copy account a prepared action other than this mode change %j", async (change) => {
    const d = deps(); d.challenge.mockResolvedValue({ operation: op, intent, masterAction: { ...masterAction, ...change } });
    await expect(runCopyAccountModeConsent(op, d)).rejects.toThrow(); expect(d.signAccount).not.toHaveBeenCalled(); expect(d.approve).not.toHaveBeenCalled();
  });
it("a copy wallet that can't sign sends nothing", async () => { const d = deps(); d.signAccount.mockRejectedValue(new Error("copy_wallet_unavailable")); await expect(runCopyAccountModeConsent(op, d)).rejects.toThrow("copy_wallet_unavailable"); expect(d.approve).not.toHaveBeenCalled(); });
