import type { Locale } from './config';

export const liveStopDiscardMessages: Record<Locale, { discard: string; hint: string; error: string; revision: string }> = {
  en: { discard: 'Discard unsent draft', hint: 'Remove this unsent draft from this device. Review the current account and mandate before making a new request.', error: 'This draft could not be discarded safely. Check its stored status before continuing.', revision: 'Mandate revision' },
  'zh-TW': { discard: '捨棄未送出的草稿', hint: '從此裝置移除這份未送出的草稿。提出新申請前，請確認目前的帳戶與授權。', error: '無法安全捨棄這份草稿。繼續前請確認其儲存狀態。', revision: '授權版本' },
  'zh-CN': { discard: '丢弃未发送的草稿', hint: '从此设备移除这份未发送的草稿。提出新申请前，请确认当前的账户与授权。', error: '无法安全丢弃这份草稿。继续前请确认其存储状态。', revision: '授权版本' },
  ko: { discard: '전송되지 않은 초안 삭제', hint: '이 기기에서 전송되지 않은 초안을 삭제합니다. 새 요청을 만들기 전에 현재 계정과 권한을 확인하세요.', error: '초안을 안전하게 삭제할 수 없습니다. 계속하기 전에 저장된 상태를 확인하세요.', revision: '권한 버전' },
  ja: { discard: '未送信の下書きを破棄', hint: 'この端末から未送信の下書きを削除します。新しい申請を行う前に、現在のアカウントと権限を確認してください。', error: '下書きを安全に破棄できません。続ける前に保存状態を確認してください。', revision: '権限のバージョン' },
  ru: { discard: 'Удалить неотправленный черновик', hint: 'Удалите неотправленный черновик с этого устройства. Перед новым запросом проверьте текущий счёт и разрешение.', error: 'Не удалось безопасно удалить черновик. Проверьте сохранённое состояние перед продолжением.', revision: 'Версия разрешения' },
  tr: { discard: 'Gönderilmemiş taslağı silin', hint: 'Bu gönderilmemiş taslağı cihazdan kaldırın. Yeni talep oluşturmadan önce mevcut hesabı ve yetkiyi inceleyin.', error: 'Taslak güvenle silinemedi. Devam etmeden önce kayıtlı durumunu kontrol edin.', revision: 'Yetki sürümü' },
  vi: { discard: 'Xóa bản nháp chưa gửi', hint: 'Xóa bản nháp chưa gửi khỏi thiết bị này. Kiểm tra tài khoản và quyền hiện tại trước khi tạo yêu cầu mới.', error: 'Không thể xóa bản nháp an toàn. Kiểm tra trạng thái đã lưu trước khi tiếp tục.', revision: 'Phiên bản quyền' },
  es: { discard: 'Descartar borrador no enviado', hint: 'Elimina este borrador no enviado del dispositivo. Revisa la cuenta y el permiso actuales antes de crear otra solicitud.', error: 'No se pudo descartar el borrador de forma segura. Revisa su estado guardado antes de continuar.', revision: 'Versión del permiso' },
  pt: { discard: 'Descartar rascunho não enviado', hint: 'Remova deste dispositivo o rascunho não enviado. Confira a conta e a autorização atuais antes de fazer um novo pedido.', error: 'Não foi possível descartar o rascunho com segurança. Verifique o estado salvo antes de continuar.', revision: 'Versão da autorização' },
  id: { discard: 'Buang draf belum terkirim', hint: 'Hapus draf belum terkirim ini dari perangkat. Periksa akun dan izin saat ini sebelum membuat permintaan baru.', error: 'Draf belum dapat dibuang dengan aman. Periksa status tersimpan sebelum melanjutkan.', revision: 'Versi izin' },
};

export const liveStopResumeMessages: Record<Locale, { resume: string; unsent: string }> = {
  en: { resume: 'Resume unsent request', unsent: 'This request was not sent. Resume the original request only with the same account and mandate revision.' },
  'zh-TW': { resume: '繼續未送出的申請', unsent: '這項申請尚未送出。僅可使用相同帳戶與授權版本繼續原始申請。' },
  'zh-CN': { resume: '继续未发送的申请', unsent: '这项申请尚未发送。仅可使用相同账户与授权版本继续原始申请。' },
  ko: { resume: '전송되지 않은 요청 재개', unsent: '이 요청은 전송되지 않았습니다. 동일한 계정과 권한 버전으로만 원래 요청을 재개할 수 있습니다.' },
  ja: { resume: '未送信の申請を再開', unsent: 'この申請は送信されていません。同じアカウントと権限のバージョンでのみ元の申請を再開できます。' },
  ru: { resume: 'Продолжить неотправленный запрос', unsent: 'Запрос не был отправлен. Продолжить исходный запрос можно только для того же счёта и версии разрешения.' },
  tr: { resume: 'Gönderilmemiş talebi sürdürün', unsent: 'Bu talep gönderilmedi. İlk talebi yalnızca aynı hesap ve yetki sürümüyle sürdürün.' },
  vi: { resume: 'Tiếp tục yêu cầu chưa gửi', unsent: 'Yêu cầu này chưa được gửi. Chỉ tiếp tục yêu cầu ban đầu với cùng tài khoản và phiên bản quyền.' },
  es: { resume: 'Reanudar solicitud no enviada', unsent: 'Esta solicitud no se envió. Reanuda la original solo con la misma cuenta y versión del permiso.' },
  pt: { resume: 'Retomar pedido não enviado', unsent: 'Este pedido não foi enviado. Retome o original somente com a mesma conta e versão da autorização.' },
  id: { resume: 'Lanjutkan permintaan belum terkirim', unsent: 'Permintaan ini belum dikirim. Lanjutkan permintaan awal hanya dengan akun dan versi izin yang sama.' },
};

const keys = ['title', 'hint', 'request', 'recover', 'working', 'signIn', 'select', 'history', 'empty', 'loading', 'error', 'storage', 'unknown', 'truncated', 'account', 'mandate', 'tracked', 'incomplete', 'issue', 'created', 'updated', 'flatTime', 'requested', 'cancelling', 'closing', 'blocked', 'flat', 'stopped', 'refresh'] as const;
export type LiveStopMessage = typeof keys[number];
type Messages = Record<LiveStopMessage, string>;
function messages(values: string[]): Messages {
  if (values.length !== keys.length) throw new Error('Invalid stop messages');
  return Object.fromEntries(keys.map((key, index) => [key, values[index]])) as Messages;
}
/** Independent resource until the stop entrypoint joins the main catalogs. */
export const liveStopMessages: Record<Locale, Messages> = {
  en: messages(['Request a stop', 'This records a stop barrier and a request to cancel orders and close positions. Order cancellation, position closure and returned funds are not confirmed by this request.', 'Request stop', 'Recover original request', 'Checking…', 'Sign in to view your stop requests.', 'Select an actual testnet mandate and its account.', 'Stop request history', 'No recorded stop requests.', 'Loading stop history…', 'Unable to verify the request. Recover the original request or refresh history; do not create another request.', 'Recovery storage is unavailable. A new request cannot be sent safely.', 'The original response needs verification. Recovery uses the saved request; a missing result does not mean the request failed.', 'Only the latest 100 requests are shown.', 'Account', 'Mandate', 'Tracked executions', 'Execution tracking is incomplete.', 'Progress needs verification. No completion is confirmed.', 'Requested', 'Updated', 'Flat position verified', 'Stop barrier recorded', 'Cancelling orders: awaiting confirmation', 'Closing positions: awaiting confirmation', 'Progress blocked', 'Flat position verified', 'Stop confirmed', 'Refresh history']),
  'zh-TW': messages(['申請停止', '這會記錄停止屏障，並申請取消訂單與平倉。這項申請不代表訂單已取消、持倉已平倉或資金已退回。', '申請停止', '查詢原始申請', '查詢中…', '登入以查看你的停止申請。', '請選擇實盤測試網授權及其帳戶。', '停止申請紀錄', '尚無停止申請紀錄。', '正在載入停止紀錄…', '無法確認申請。請查詢原始申請或重新整理紀錄，勿建立另一項申請。', '復原儲存空間無法使用，無法安全送出新申請。', '原始回應仍需確認。查詢會使用已儲存的申請；找不到結果不代表申請失敗。', '僅顯示最近 100 項申請。', '帳戶', '授權', '已追蹤執行', '執行追蹤尚未完整。', '進度需要確認，目前未確認完成。', '申請時間', '更新時間', '確認平倉時間', '已記錄停止屏障', '取消訂單中：等待確認', '平倉中：等待確認', '進度受阻', '已確認平倉', '已確認停止', '重新整理紀錄']),
  'zh-CN': messages(['申请停止', '这会记录停止屏障，并申请取消订单与平仓。这项申请不代表订单已取消、持仓已平仓或资金已退回。', '申请停止', '查询原始申请', '查询中…', '登录以查看你的停止申请。', '请选择实盘测试网授权及其账户。', '停止申请记录', '暂无停止申请记录。', '正在加载停止记录…', '无法确认申请。请查询原始申请或刷新记录，勿建立另一项申请。', '恢复存储无法使用，无法安全发送新申请。', '原始响应仍需确认。查询会使用已保存的申请；找不到结果不代表申请失败。', '仅显示最近 100 项申请。', '账户', '授权', '已跟踪执行', '执行跟踪尚未完整。', '进度需要确认，目前未确认完成。', '申请时间', '更新时间', '确认平仓时间', '已记录停止屏障', '取消订单中：等待确认', '平仓中：等待确认', '进度受阻', '已确认平仓', '已确认停止', '刷新记录']),
  ko: messages(['중지 요청', '중지 장벽과 주문 취소 및 포지션 종료 요청을 기록합니다. 이 요청만으로 주문 취소, 포지션 종료 또는 자금 반환이 확인되지는 않습니다.', '중지 요청', '원래 요청 조회', '확인 중…', '중지 요청을 보려면 로그인하세요.', '실거래 테스트넷 권한과 해당 계정을 선택하세요.', '중지 요청 기록', '기록된 중지 요청이 없습니다.', '중지 기록을 불러오는 중…', '요청을 확인할 수 없습니다. 원래 요청을 조회하거나 기록을 새로고침하세요. 새 요청을 만들지 마세요.', '복구 저장소를 사용할 수 없어 새 요청을 안전하게 보낼 수 없습니다.', '원래 응답을 확인해야 합니다. 저장된 요청으로 조회하며, 결과가 없다고 요청이 실패한 것은 아닙니다.', '최근 요청 100개만 표시됩니다.', '계정', '권한', '추적된 실행', '실행 추적이 완료되지 않았습니다.', '진행 상황 확인이 필요합니다. 완료는 확인되지 않았습니다.', '요청 시간', '갱신 시간', '포지션 종료 확인', '중지 장벽 기록됨', '주문 취소 중: 확인 대기', '포지션 종료 중: 확인 대기', '진행 차단됨', '포지션 종료 확인됨', '중지 확인됨', '기록 새로고침']),
  ja: messages(['停止を申請', '停止の制限と注文キャンセル・ポジション決済の申請を記録します。この申請だけでは注文のキャンセル、決済、資金の返還は確認されません。', '停止を申請', '元の申請を確認', '確認中…', '停止申請を表示するにはログインしてください。', '実取引のテストネット権限と対応するアカウントを選択してください。', '停止申請の履歴', '停止申請の記録はありません。', '停止履歴を読み込み中…', '申請を確認できません。元の申請を確認するか履歴を更新してください。別の申請を作成しないでください。', '復元用の保存領域が利用できないため、新しい申請を安全に送信できません。', '元の応答の確認が必要です。保存済みの申請を照会します。結果がなくても申請の失敗を意味しません。', '直近100件の申請のみ表示されます。', 'アカウント', '権限', '追跡済みの実行', '実行の追跡は未完了です。', '進捗の確認が必要です。完了は確認されていません。', '申請日時', '更新日時', '決済確認日時', '停止の制限を記録済み', '注文キャンセル中：確認待ち', 'ポジション決済中：確認待ち', '進行がブロックされています', '決済を確認済み', '停止を確認済み', '履歴を更新']),
  ru: messages(['Запрос остановки', 'Записываются барьер остановки и запрос отмены ордеров и закрытия позиций. Этот запрос не подтверждает отмену, закрытие или возврат средств.', 'Запросить остановку', 'Проверить исходный запрос', 'Проверка…', 'Войдите, чтобы увидеть ваши запросы остановки.', 'Выберите разрешение реальной торговли в тестовой сети и его счёт.', 'История запросов остановки', 'Запросов остановки пока нет.', 'Загрузка истории…', 'Не удалось проверить запрос. Проверьте исходный запрос или обновите историю. Не создавайте новый запрос.', 'Хранилище восстановления недоступно. Новый запрос нельзя безопасно отправить.', 'Исходный ответ требует проверки. Используется сохранённый запрос; отсутствие результата не означает отказ.', 'Показаны только последние 100 запросов.', 'Счёт', 'Разрешение', 'Отслеживаемые исполнения', 'Отслеживание исполнений неполное.', 'Нужна проверка прогресса. Завершение не подтверждено.', 'Запрошено', 'Обновлено', 'Закрытие позиции проверено', 'Барьер остановки записан', 'Отмена ордеров: ожидается подтверждение', 'Закрытие позиций: ожидается подтверждение', 'Процесс заблокирован', 'Закрытие позиции проверено', 'Остановка подтверждена', 'Обновить историю']),
  tr: messages(['Durdurma talebi', 'Durdurma engeli ve emir iptali ile pozisyon kapatma talebi kaydedilir. Bu talep emir iptalini, pozisyonların kapatılmasını veya fonların iadesini doğrulamaz.', 'Durdurma talep edin', 'İlk talebi kontrol edin', 'Kontrol ediliyor…', 'Durdurma taleplerinizi görmek için giriş yapın.', 'Gerçek işlem test ağı yetkisini ve hesabını seçin.', 'Durdurma talebi geçmişi', 'Kayıtlı durdurma talebi yok.', 'Geçmiş yükleniyor…', 'Talep doğrulanamadı. İlk talebi kontrol edin veya geçmişi yenileyin; yeni talep oluşturmayın.', 'Kurtarma depolaması kullanılamıyor. Yeni talep güvenle gönderilemez.', 'İlk yanıt doğrulanmalıdır. Kaydedilen talep sorgulanır; sonuç bulunamaması talebin başarısız olduğu anlamına gelmez.', 'Yalnızca son 100 talep gösterilir.', 'Hesap', 'Yetki', 'Takip edilen işlemler', 'İşlem takibi tamamlanmadı.', 'İlerleme doğrulanmalıdır. Tamamlanma onaylanmadı.', 'Talep zamanı', 'Güncelleme', 'Pozisyon kapanışı doğrulandı', 'Durdurma engeli kaydedildi', 'Emirler iptal ediliyor: onay bekleniyor', 'Pozisyonlar kapatılıyor: onay bekleniyor', 'İlerleme engellendi', 'Pozisyon kapanışı doğrulandı', 'Durdurma onaylandı', 'Geçmişi yenileyin']),
  vi: messages(['Yêu cầu dừng', 'Ghi lại rào chắn dừng và yêu cầu hủy lệnh, đóng vị thế. Yêu cầu này không xác nhận lệnh đã hủy, vị thế đã đóng hoặc tiền đã hoàn trả.', 'Yêu cầu dừng', 'Kiểm tra yêu cầu ban đầu', 'Đang kiểm tra…', 'Đăng nhập để xem yêu cầu dừng của bạn.', 'Chọn quyền giao dịch thực trên mạng thử nghiệm và tài khoản tương ứng.', 'Lịch sử yêu cầu dừng', 'Chưa có yêu cầu dừng được ghi nhận.', 'Đang tải lịch sử…', 'Không thể xác minh yêu cầu. Kiểm tra yêu cầu ban đầu hoặc tải lại lịch sử; đừng tạo yêu cầu mới.', 'Không thể dùng bộ nhớ khôi phục. Không thể gửi yêu cầu mới an toàn.', 'Cần xác minh phản hồi ban đầu. Tra cứu dùng yêu cầu đã lưu; không có kết quả không có nghĩa yêu cầu thất bại.', 'Chỉ hiển thị 100 yêu cầu gần nhất.', 'Tài khoản', 'Quyền', 'Lần thực hiện được theo dõi', 'Theo dõi thực hiện chưa đầy đủ.', 'Cần xác minh tiến độ. Chưa xác nhận hoàn tất.', 'Thời gian yêu cầu', 'Cập nhật', 'Đã xác minh đóng vị thế', 'Đã ghi nhận rào chắn dừng', 'Đang hủy lệnh: chờ xác nhận', 'Đang đóng vị thế: chờ xác nhận', 'Tiến độ bị chặn', 'Đã xác minh đóng vị thế', 'Đã xác nhận dừng', 'Tải lại lịch sử']),
  es: messages(['Solicitar detención', 'Se registra una barrera de detención y una solicitud para cancelar órdenes y cerrar posiciones. Esta solicitud no confirma la cancelación, el cierre ni la devolución de fondos.', 'Solicitar detención', 'Consultar solicitud original', 'Comprobando…', 'Inicia sesión para ver tus solicitudes.', 'Selecciona un permiso real en la red de pruebas y su cuenta.', 'Historial de solicitudes de detención', 'No hay solicitudes registradas.', 'Cargando historial…', 'No se pudo verificar la solicitud. Consulta la original o actualiza el historial; no crees otra solicitud.', 'El almacenamiento de recuperación no está disponible. No se puede enviar una nueva solicitud de forma segura.', 'La respuesta original necesita verificación. Se consulta la solicitud guardada; que no haya resultado no significa que haya fallado.', 'Solo se muestran las últimas 100 solicitudes.', 'Cuenta', 'Permiso', 'Ejecuciones registradas', 'El seguimiento de ejecuciones está incompleto.', 'El progreso necesita verificación. No se confirma que haya terminado.', 'Solicitada', 'Actualizada', 'Cierre de posición verificado', 'Barrera de detención registrada', 'Cancelando órdenes: pendiente de confirmación', 'Cerrando posiciones: pendiente de confirmación', 'Progreso bloqueado', 'Cierre de posición verificado', 'Detención confirmada', 'Actualizar historial']),
  pt: messages(['Solicitar parada', 'Registra uma barreira de parada e um pedido para cancelar ordens e fechar posições. O pedido não confirma cancelamento, fechamento ou devolução de fundos.', 'Solicitar parada', 'Consultar pedido original', 'Verificando…', 'Entre para ver seus pedidos de parada.', 'Selecione uma autorização real na rede de testes e sua conta.', 'Histórico de pedidos de parada', 'Nenhum pedido registrado.', 'Carregando histórico…', 'Não foi possível verificar o pedido. Consulte o original ou atualize o histórico; não crie outro pedido.', 'O armazenamento de recuperação está indisponível. Não é seguro enviar um novo pedido.', 'A resposta original precisa ser verificada. A consulta usa o pedido salvo; a ausência de resultado não significa falha.', 'Somente os últimos 100 pedidos são exibidos.', 'Conta', 'Autorização', 'Execuções acompanhadas', 'O acompanhamento de execuções está incompleto.', 'O progresso precisa ser verificado. A conclusão não foi confirmada.', 'Solicitado', 'Atualizado', 'Fechamento da posição verificado', 'Barreira de parada registrada', 'Cancelando ordens: aguardando confirmação', 'Fechando posições: aguardando confirmação', 'Progresso bloqueado', 'Fechamento da posição verificado', 'Parada confirmada', 'Atualizar histórico']),
  id: messages(['Minta penghentian', 'Ini mencatat penghalang penghentian dan permintaan pembatalan order serta penutupan posisi. Permintaan ini tidak mengonfirmasi pembatalan, penutupan, atau pengembalian dana.', 'Minta penghentian', 'Periksa permintaan awal', 'Memeriksa…', 'Masuk untuk melihat permintaan penghentian kamu.', 'Pilih izin perdagangan nyata di jaringan uji dan akunnya.', 'Riwayat permintaan penghentian', 'Belum ada permintaan tercatat.', 'Memuat riwayat…', 'Permintaan belum dapat diverifikasi. Periksa permintaan awal atau muat ulang riwayat; jangan buat permintaan baru.', 'Penyimpanan pemulihan tidak tersedia. Permintaan baru tidak dapat dikirim dengan aman.', 'Respons awal perlu diverifikasi. Pemeriksaan memakai permintaan tersimpan; hasil yang tidak ditemukan bukan berarti permintaan gagal.', 'Hanya 100 permintaan terbaru yang ditampilkan.', 'Akun', 'Izin', 'Eksekusi terlacak', 'Pelacakan eksekusi belum lengkap.', 'Progres perlu diverifikasi. Penyelesaian belum dikonfirmasi.', 'Diminta', 'Diperbarui', 'Penutupan posisi terverifikasi', 'Penghalang penghentian tercatat', 'Membatalkan order: menunggu konfirmasi', 'Menutup posisi: menunggu konfirmasi', 'Progres terhambat', 'Penutupan posisi terverifikasi', 'Penghentian terkonfirmasi', 'Muat ulang riwayat']),
};
