import type { Locale } from './config';
import type { LiveCopyStage } from '@trading-dashboard/shared/contracts';

export interface LiveCopiesText {
  title: string; testnet: string; mainnetLeader: string; testnetLeader: string;
  stages: Record<LiveCopyStage, string>; hints: Record<LiveCopyStage, string>;
  equity: string; withdrawable: string; positions: string; noPositions: string; size: string; entry: string; pnl: string;
  close: string; closing: string; setup: string; deposit: string; withdraw: string; amount: string; withdrawConfirm: string; returnAll: string;
  consent: string; consentHint: string; refusal: string; priceDeviation: string; transfer: string;
  /** A transfer in flight, in words: which way, and how far it got. */
  transferDirection: Record<'to_account' | 'to_main', string>; transferStatus: Record<'prepared' | 'unknown' | 'accepted', string>; unobserved: string; error: string; busy: string; cancelReturn: string;
  /** Accounts with the automatic return (worker-signed sweep after a stop). */
  autoReturning: string; autoReturningHint: string; returned: string;
  /** The withdraw box and the confirm sheet of every withdrawal, return and stop. */
  ui: Record<'amountPlaceholder' | 'maxWithdrawable' | 'all' | 'transferPending' | 'details' | 'copyAddress' | 'withdrawTitle' | 'returnTitle' | 'stopTitle' | 'amountRow' | 'allAmount' | 'destination' | 'mainWallet' | 'network' | 'eta' | 'etaValue' | 'confirmWithdraw' | 'confirmReturn' | 'confirmStop' | 'cancel', string>;
}

export const liveCopiesMessages: Record<Locale, LiveCopiesText> = {
  en: { ui: { amountPlaceholder: "Enter amount", maxWithdrawable: "Up to {amount}", all: "All", transferPending: "Transfer in progress; you can withdraw again once it completes", details: "Details", copyAddress: "Copy address", withdrawTitle: "Confirm withdrawal", returnTitle: "Confirm return of all funds", stopTitle: "Confirm stop", amountRow: "Amount", allAmount: "All (about {amount})", destination: "To", mainWallet: "Your main wallet", network: "Network", eta: "Expected time", etaValue: "About 1 minute", confirmWithdraw: "Confirm withdrawal", confirmReturn: "Confirm return", confirmStop: "Confirm stop", cancel: "Cancel" },
    title: 'Testnet copies', testnet: 'Testnet', mainnetLeader: 'Mainnet leader', testnetLeader: 'Testnet leader',
    stages: { setup: 'Finish setup', needs_deposit: 'Needs deposit', funding: 'Funding', awaiting_credit: 'Awaiting credit', starting: 'Starting', active: 'Active', paused: 'Paused', stopping: 'Stopping', sweeping: 'Returning funds', stopped: 'Stopped' },
    hints: { setup: 'Prepare the copy wallet, its trading agent and your consent in Settings.', needs_deposit: 'Deposit USDC from your main wallet to start copying.', funding: 'Your deposit is being signed and sent.', awaiting_credit: 'Deposit sent; waiting for Hyperliquid to credit it.', starting: 'Funded. Copying starts within seconds.', active: 'Copying the leader’s trades on Hyperliquid testnet.', paused: 'New trades are paused.', stopping: 'Closing positions. Open orders and positions are being wound down.', sweeping: 'Flat. Return the funds to your main wallet to finish.', stopped: 'This copy has ended.' },
    equity: 'Equity', withdrawable: 'Withdrawable', positions: 'Positions', noPositions: 'No open positions', size: 'Size', entry: 'Entry', pnl: 'Unrealized PnL',
    close: 'Close', closing: 'Closing…', setup: 'Open setup', deposit: 'Deposit', withdraw: 'Withdraw idle funds', amount: 'Amount (USDC)', withdrawConfirm: 'Sign and withdraw',
    returnAll: 'Return all to main wallet', consent: 'Sign consent to cancel orders', consentHint: 'The stop found open orders. Your main wallet signs a consent that lets Orbie cancel only those orders.',
    refusal: 'Last skipped signal: {reason}', priceDeviation: 'price too far from the trader’s fill', transfer: '{direction} · {status}: {amount} USDC', transferDirection: { to_account: 'Deposit', to_main: 'Return to main wallet' }, transferStatus: { prepared: 'waiting to be sent', unknown: 'being confirmed', accepted: 'sent, waiting for credit' }, unobserved: 'Balances not observed yet.',
    error: 'The action did not complete. Check the copy and try again.', busy: 'Working…', cancelReturn: 'Cancel this return', autoReturning: 'Returning automatically', autoReturningHint: 'Flat. The funds are on their way back to your main wallet; nothing to sign.', returned: 'Returned {amount} USDC to your main wallet' },
  'zh-TW': { ui: { amountPlaceholder: "輸入金額", maxWithdrawable: "最多可提款 {amount}", all: "全部", transferPending: "轉帳處理中，完成後可再次提款", details: "詳細資料", copyAddress: "複製地址", withdrawTitle: "確認提款", returnTitle: "確認全部返還", stopTitle: "確認停止跟單", amountRow: "金額", allAmount: "全部（約 {amount}）", destination: "目的地", mainWallet: "你的主錢包", network: "網路", eta: "預計時間", etaValue: "約 1 分鐘", confirmWithdraw: "確認提款", confirmReturn: "確認返還", confirmStop: "確認停止", cancel: "取消" },
    title: '測試網跟單', testnet: '測試網', mainnetLeader: '主網交易員', testnetLeader: '測試網交易員',
    stages: { setup: '完成設定', needs_deposit: '待入金', funding: '入金中', awaiting_credit: '等待入帳', starting: '即將開始', active: '跟單中', paused: '已暫停', stopping: '停止中', sweeping: '資金返還中', stopped: '已停止' },
    hints: { setup: '請在設定中準備跟單錢包、交易代理與您的同意。', needs_deposit: '從主錢包入金 USDC 後開始跟單。', funding: '入金正在簽署與送出。', awaiting_credit: '入金已送出，等待 Hyperliquid 入帳。', starting: '已入金，數秒內開始跟單。', active: '正在 Hyperliquid 測試網跟隨交易員的交易。', paused: '已暫停新交易。', stopping: '正在平倉，委託與持倉正在收尾。', sweeping: '已無持倉。將資金返還主錢包即可完成。', stopped: '此跟單已結束。' },
    equity: '權益', withdrawable: '可提款', positions: '持倉', noPositions: '沒有持倉', size: '數量', entry: '開倉價', pnl: '未實現盈虧',
    close: '平倉', closing: '平倉中…', setup: '前往設定', deposit: '入金', withdraw: '提款', amount: '金額（USDC）', withdrawConfirm: '簽署並提款',
    returnAll: '全部返還主錢包', consent: '簽署撤單同意', consentHint: '停止時發現未成交委託。由主錢包簽署同意，Orbie 只會取消這些委託。',
    refusal: '最近略過的訊號：{reason}', priceDeviation: '價格與交易員成交價差距過大', transfer: '{direction}・{status}：{amount} USDC', transferDirection: { to_account: '入金', to_main: '返還主錢包' }, transferStatus: { prepared: '等待送出', unknown: '確認中', accepted: '已送出，等待入帳' }, unobserved: '尚未取得帳戶餘額。',
    error: '操作未完成，請檢查此跟單後再試。', busy: '處理中…', cancelReturn: '取消這筆轉回', autoReturning: '自動返還中', autoReturningHint: '已無持倉，資金正自動返還主錢包，不需簽署。', returned: '已返還 {amount} USDC 至主錢包' },
  'zh-CN': { ui: { amountPlaceholder: "输入金额", maxWithdrawable: "最多可提取 {amount}", all: "全部", transferPending: "转账处理中，完成后可再次提取", details: "详细信息", copyAddress: "复制地址", withdrawTitle: "确认提取", returnTitle: "确认全部返还", stopTitle: "确认停止跟单", amountRow: "金额", allAmount: "全部（约 {amount}）", destination: "目的地", mainWallet: "你的主钱包", network: "网络", eta: "预计时间", etaValue: "约 1 分钟", confirmWithdraw: "确认提取", confirmReturn: "确认返还", confirmStop: "确认停止", cancel: "取消" },
    title: '测试网跟单', testnet: '测试网', mainnetLeader: '主网交易员', testnetLeader: '测试网交易员',
    stages: { setup: '完成设置', needs_deposit: '待入金', funding: '入金中', awaiting_credit: '等待到账', starting: '即将开始', active: '跟单中', paused: '已暂停', stopping: '停止中', sweeping: '资金返还中', stopped: '已停止' },
    hints: { setup: '请在设置中准备跟单钱包、交易代理与您的同意。', needs_deposit: '从主钱包入金 USDC 后开始跟单。', funding: '入金正在签名与发送。', awaiting_credit: '入金已发送，等待 Hyperliquid 到账。', starting: '已入金，数秒内开始跟单。', active: '正在 Hyperliquid 测试网跟随交易员的交易。', paused: '已暂停新交易。', stopping: '正在平仓，委托与持仓正在收尾。', sweeping: '已无持仓。将资金返还主钱包即可完成。', stopped: '此跟单已结束。' },
    equity: '权益', withdrawable: '可提取', positions: '持仓', noPositions: '没有持仓', size: '数量', entry: '开仓价', pnl: '未实现盈亏',
    close: '平仓', closing: '平仓中…', setup: '前往设置', deposit: '入金', withdraw: '提取闲置资金', amount: '金额（USDC）', withdrawConfirm: '签名并提取',
    returnAll: '全部返还主钱包', consent: '签署撤单同意', consentHint: '停止时发现未成交委托。由主钱包签署同意，Orbie 只会取消这些委托。',
    refusal: '最近跳过的信号：{reason}', priceDeviation: '价格与交易员成交价差距过大', transfer: '{direction}・{status}：{amount} USDC', transferDirection: { to_account: '入金', to_main: '返还主钱包' }, transferStatus: { prepared: '等待发送', unknown: '确认中', accepted: '已发送，等待到账' }, unobserved: '尚未获取账户余额。',
    error: '操作未完成，请检查此跟单后重试。', busy: '处理中…', cancelReturn: '取消这笔转回', autoReturning: '自动返还中', autoReturningHint: '已无持仓，资金正自动返还主钱包，无需签名。', returned: '已返还 {amount} USDC 至主钱包' },
  ko: { ui: { amountPlaceholder: "금액 입력", maxWithdrawable: "최대 {amount}", all: "전액", transferPending: "이체 처리 중입니다. 완료 후 다시 출금할 수 있습니다", details: "상세 정보", copyAddress: "주소 복사", withdrawTitle: "출금 확인", returnTitle: "전액 반환 확인", stopTitle: "카피 중지 확인", amountRow: "금액", allAmount: "전액 (약 {amount})", destination: "받는 곳", mainWallet: "내 메인 지갑", network: "네트워크", eta: "예상 시간", etaValue: "약 1분", confirmWithdraw: "출금 확인", confirmReturn: "반환 확인", confirmStop: "중지 확인", cancel: "취소" },
    title: '테스트넷 카피', testnet: '테스트넷', mainnetLeader: '메인넷 트레이더', testnetLeader: '테스트넷 트레이더',
    stages: { setup: '설정 완료 필요', needs_deposit: '입금 필요', funding: '입금 중', awaiting_credit: '입금 확인 대기', starting: '곧 시작', active: '카피 중', paused: '일시 정지', stopping: '중지 중', sweeping: '자금 반환 중', stopped: '중지됨' },
    hints: { setup: '설정에서 카피 지갑, 트레이딩 에이전트와 동의를 준비하세요.', needs_deposit: '메인 지갑에서 USDC를 입금하면 카피가 시작됩니다.', funding: '입금에 서명하고 전송하는 중입니다.', awaiting_credit: '입금을 보냈습니다. Hyperliquid 반영을 기다리는 중입니다.', starting: '입금 완료. 몇 초 안에 카피를 시작합니다.', active: 'Hyperliquid 테스트넷에서 트레이더의 거래를 따라가는 중입니다.', paused: '새 거래가 일시 정지되었습니다.', stopping: '포지션을 정리하는 중입니다. 주문과 포지션을 마무리합니다.', sweeping: '포지션 없음. 자금을 메인 지갑으로 반환하면 완료됩니다.', stopped: '이 카피는 종료되었습니다.' },
    equity: '자산', withdrawable: '출금 가능', positions: '포지션', noPositions: '보유 포지션 없음', size: '수량', entry: '진입가', pnl: '미실현 손익',
    close: '청산', closing: '청산 중…', setup: '설정 열기', deposit: '입금', withdraw: '유휴 자금 출금', amount: '금액 (USDC)', withdrawConfirm: '서명 후 출금',
    returnAll: '전액 메인 지갑으로 반환', consent: '주문 취소 동의 서명', consentHint: '중지 중 미체결 주문이 발견되었습니다. 메인 지갑으로 동의에 서명하면 Orbie는 해당 주문만 취소합니다.',
    refusal: '최근 건너뛴 신호: {reason}', priceDeviation: '가격이 트레이더 체결가와 너무 다름', transfer: '{direction} · {status}: {amount} USDC', transferDirection: { to_account: '입금', to_main: '메인 지갑으로 반환' }, transferStatus: { prepared: '전송 대기', unknown: '확인 중', accepted: '전송됨, 반영 대기' }, unobserved: '아직 잔고를 확인하지 못했습니다.',
    error: '작업이 완료되지 않았습니다. 카피를 확인하고 다시 시도하세요.', busy: '처리 중…', cancelReturn: '이 반환 취소', autoReturning: '자동 반환 중', autoReturningHint: '포지션 없음. 자금이 메인 지갑으로 자동 반환되는 중이며 서명할 필요가 없습니다.', returned: '메인 지갑으로 {amount} USDC 반환됨' },
  ja: { ui: { amountPlaceholder: "金額を入力", maxWithdrawable: "最大 {amount}", all: "全額", transferPending: "送金処理中です。完了後に再度出金できます", details: "詳細", copyAddress: "アドレスをコピー", withdrawTitle: "出金の確認", returnTitle: "全額返還の確認", stopTitle: "コピー停止の確認", amountRow: "金額", allAmount: "全額（約 {amount}）", destination: "送金先", mainWallet: "あなたのメインウォレット", network: "ネットワーク", eta: "所要時間", etaValue: "約 1 分", confirmWithdraw: "出金を確定", confirmReturn: "返還を確定", confirmStop: "停止を確定", cancel: "キャンセル" },
    title: 'テストネットのコピー', testnet: 'テストネット', mainnetLeader: 'メインネットのトレーダー', testnetLeader: 'テストネットのトレーダー',
    stages: { setup: '設定を完了', needs_deposit: '入金待ち', funding: '入金中', awaiting_credit: '着金待ち', starting: 'まもなく開始', active: 'コピー中', paused: '一時停止中', stopping: '停止中', sweeping: '資金返還中', stopped: '停止済み' },
    hints: { setup: '設定でコピー用ウォレット、取引エージェント、同意を準備してください。', needs_deposit: 'メインウォレットから USDC を入金するとコピーが始まります。', funding: '入金を署名して送信しています。', awaiting_credit: '入金済み。Hyperliquid の着金を待っています。', starting: '入金完了。数秒でコピーを開始します。', active: 'Hyperliquid テストネットでトレーダーの取引をコピーしています。', paused: '新規取引は一時停止中です。', stopping: 'ポジションを決済しています。注文とポジションを整理中です。', sweeping: 'ポジションなし。資金をメインウォレットに戻すと完了します。', stopped: 'このコピーは終了しました。' },
    equity: '資産', withdrawable: '出金可能', positions: 'ポジション', noPositions: 'ポジションはありません', size: '数量', entry: '建値', pnl: '含み損益',
    close: '決済', closing: '決済中…', setup: '設定を開く', deposit: '入金', withdraw: '余剰資金を出金', amount: '金額（USDC）', withdrawConfirm: '署名して出金',
    returnAll: '全額をメインウォレットに戻す', consent: '注文取消の同意に署名', consentHint: '停止時に未約定の注文が見つかりました。メインウォレットで同意に署名すると、Orbie はその注文だけを取り消します。',
    refusal: '直近でスキップしたシグナル：{reason}', priceDeviation: '価格がトレーダーの約定価格と大きく乖離', transfer: '{direction}・{status}：{amount} USDC', transferDirection: { to_account: '入金', to_main: 'メインウォレットへ返還' }, transferStatus: { prepared: '送信待ち', unknown: '確認中', accepted: '送信済み、着金待ち' }, unobserved: '残高をまだ取得できていません。',
    error: '操作が完了しませんでした。コピーを確認して再試行してください。', busy: '処理中…', cancelReturn: 'この返金を取り消す', autoReturning: '自動返還中', autoReturningHint: 'ポジションなし。資金はメインウォレットへ自動で戻っています。署名は不要です。', returned: '{amount} USDC をメインウォレットに返還しました' },
  ru: { ui: { amountPlaceholder: "Введите сумму", maxWithdrawable: "До {amount}", all: "Всё", transferPending: "Перевод выполняется; вывести снова можно после его завершения", details: "Подробности", copyAddress: "Скопировать адрес", withdrawTitle: "Подтвердите вывод", returnTitle: "Подтвердите возврат всех средств", stopTitle: "Подтвердите остановку", amountRow: "Сумма", allAmount: "Всё (около {amount})", destination: "Куда", mainWallet: "Ваш основной кошелёк", network: "Сеть", eta: "Ожидаемое время", etaValue: "Около 1 минуты", confirmWithdraw: "Подтвердить вывод", confirmReturn: "Подтвердить возврат", confirmStop: "Подтвердить остановку", cancel: "Отмена" },
    title: 'Копирование в тестнете', testnet: 'Тестнет', mainnetLeader: 'Трейдер мейннета', testnetLeader: 'Трейдер тестнета',
    stages: { setup: 'Завершите настройку', needs_deposit: 'Нужен депозит', funding: 'Пополнение', awaiting_credit: 'Ожидание зачисления', starting: 'Запуск', active: 'Копирует', paused: 'Пауза', stopping: 'Остановка', sweeping: 'Возврат средств', stopped: 'Остановлено' },
    hints: { setup: 'Подготовьте кошелёк копии, торгового агента и согласие в настройках.', needs_deposit: 'Внесите USDC с основного кошелька, чтобы начать копирование.', funding: 'Депозит подписывается и отправляется.', awaiting_credit: 'Депозит отправлен; ждём зачисления в Hyperliquid.', starting: 'Средства зачислены. Копирование начнётся через несколько секунд.', active: 'Сделки трейдера копируются в тестнете Hyperliquid.', paused: 'Новые сделки приостановлены.', stopping: 'Позиции закрываются, ордера и позиции сворачиваются.', sweeping: 'Позиций нет. Верните средства на основной кошелёк, чтобы завершить.', stopped: 'Это копирование завершено.' },
    equity: 'Капитал', withdrawable: 'Доступно к выводу', positions: 'Позиции', noPositions: 'Открытых позиций нет', size: 'Размер', entry: 'Вход', pnl: 'Нереализованный PnL',
    close: 'Закрыть', closing: 'Закрытие…', setup: 'Открыть настройки', deposit: 'Пополнить', withdraw: 'Вывести свободные средства', amount: 'Сумма (USDC)', withdrawConfirm: 'Подписать и вывести',
    returnAll: 'Вернуть всё на основной кошелёк', consent: 'Подписать согласие на отмену ордеров', consentHint: 'При остановке найдены открытые ордера. Основной кошелёк подписывает согласие, и Orbie отменит только их.',
    refusal: 'Последний пропущенный сигнал: {reason}', priceDeviation: 'цена слишком далека от цены сделки трейдера', transfer: '{direction} · {status}: {amount} USDC', transferDirection: { to_account: 'Депозит', to_main: 'Возврат на основной кошелёк' }, transferStatus: { prepared: 'ожидает отправки', unknown: 'подтверждается', accepted: 'отправлен, ждёт зачисления' }, unobserved: 'Баланс ещё не получен.',
    error: 'Действие не завершено. Проверьте копирование и повторите.', busy: 'Выполняется…', cancelReturn: 'Отменить этот возврат', autoReturning: 'Автоматический возврат', autoReturningHint: 'Позиций нет. Средства автоматически возвращаются на основной кошелёк, подписывать ничего не нужно.', returned: 'Возвращено {amount} USDC на основной кошелёк' },
  tr: { ui: { amountPlaceholder: "Tutar girin", maxWithdrawable: "En fazla {amount}", all: "Tümü", transferPending: "Transfer sürüyor; tamamlanınca yeniden çekebilirsiniz", details: "Ayrıntılar", copyAddress: "Adresi kopyala", withdrawTitle: "Çekimi onaylayın", returnTitle: "Tüm fonların iadesini onaylayın", stopTitle: "Durdurmayı onaylayın", amountRow: "Tutar", allAmount: "Tümü (yaklaşık {amount})", destination: "Alıcı", mainWallet: "Ana cüzdanınız", network: "Ağ", eta: "Tahmini süre", etaValue: "Yaklaşık 1 dakika", confirmWithdraw: "Çekimi onayla", confirmReturn: "İadeyi onayla", confirmStop: "Durdurmayı onayla", cancel: "İptal" },
    title: 'Testnet kopyaları', testnet: 'Testnet', mainnetLeader: 'Mainnet trader', testnetLeader: 'Testnet trader',
    stages: { setup: 'Kurulumu tamamlayın', needs_deposit: 'Yatırım gerekli', funding: 'Yatırılıyor', awaiting_credit: 'Hesaba geçmesi bekleniyor', starting: 'Başlıyor', active: 'Kopyalanıyor', paused: 'Duraklatıldı', stopping: 'Durduruluyor', sweeping: 'Fonlar iade ediliyor', stopped: 'Durduruldu' },
    hints: { setup: 'Ayarlar’da kopya cüzdanını, işlem ajanını ve onayınızı hazırlayın.', needs_deposit: 'Kopyalamaya başlamak için ana cüzdandan USDC yatırın.', funding: 'Yatırma işlemi imzalanıp gönderiliyor.', awaiting_credit: 'Yatırma gönderildi; Hyperliquid’in hesaba geçirmesi bekleniyor.', starting: 'Fonlandı. Kopyalama birkaç saniye içinde başlar.', active: 'Trader’ın işlemleri Hyperliquid testnet’te kopyalanıyor.', paused: 'Yeni işlemler duraklatıldı.', stopping: 'Pozisyonlar kapatılıyor; emirler ve pozisyonlar sonlandırılıyor.', sweeping: 'Pozisyon yok. Bitirmek için fonları ana cüzdana iade edin.', stopped: 'Bu kopya sona erdi.' },
    equity: 'Varlık', withdrawable: 'Çekilebilir', positions: 'Pozisyonlar', noPositions: 'Açık pozisyon yok', size: 'Miktar', entry: 'Giriş', pnl: 'Gerçekleşmemiş K/Z',
    close: 'Kapat', closing: 'Kapatılıyor…', setup: 'Ayarları aç', deposit: 'Yatır', withdraw: 'Boştaki fonları çek', amount: 'Tutar (USDC)', withdrawConfirm: 'İmzala ve çek',
    returnAll: 'Tümünü ana cüzdana iade et', consent: 'Emir iptali onayını imzala', consentHint: 'Durdurma sırasında açık emirler bulundu. Ana cüzdanınız bir onay imzalar ve Orbie yalnızca bu emirleri iptal eder.',
    refusal: 'Son atlanan sinyal: {reason}', priceDeviation: 'fiyat, trader’ın işlem fiyatından çok uzak', transfer: '{direction} · {status}: {amount} USDC', transferDirection: { to_account: 'Yatırma', to_main: 'Ana cüzdana iade' }, transferStatus: { prepared: 'gönderilmeyi bekliyor', unknown: 'onaylanıyor', accepted: 'gönderildi, hesaba geçmesi bekleniyor' }, unobserved: 'Bakiyeler henüz okunmadı.',
    error: 'İşlem tamamlanmadı. Kopyayı kontrol edip tekrar deneyin.', busy: 'İşleniyor…', cancelReturn: 'Bu iadeyi iptal et', autoReturning: 'Otomatik iade ediliyor', autoReturningHint: 'Pozisyon yok. Fonlar ana cüzdanınıza otomatik olarak dönüyor; imzalamanız gerekmiyor.', returned: 'Ana cüzdanınıza {amount} USDC iade edildi' },
  vi: { ui: { amountPlaceholder: "Nhập số tiền", maxWithdrawable: "Tối đa {amount}", all: "Tất cả", transferPending: "Đang chuyển tiền; có thể rút tiếp khi hoàn tất", details: "Chi tiết", copyAddress: "Sao chép địa chỉ", withdrawTitle: "Xác nhận rút tiền", returnTitle: "Xác nhận hoàn trả toàn bộ", stopTitle: "Xác nhận dừng sao chép", amountRow: "Số tiền", allAmount: "Tất cả (khoảng {amount})", destination: "Đến", mainWallet: "Ví chính của bạn", network: "Mạng", eta: "Thời gian dự kiến", etaValue: "Khoảng 1 phút", confirmWithdraw: "Xác nhận rút", confirmReturn: "Xác nhận hoàn trả", confirmStop: "Xác nhận dừng", cancel: "Hủy" },
    title: 'Sao chép trên testnet', testnet: 'Testnet', mainnetLeader: 'Trader mainnet', testnetLeader: 'Trader testnet',
    stages: { setup: 'Hoàn tất thiết lập', needs_deposit: 'Cần nạp tiền', funding: 'Đang nạp', awaiting_credit: 'Chờ ghi có', starting: 'Sắp bắt đầu', active: 'Đang sao chép', paused: 'Tạm dừng', stopping: 'Đang dừng', sweeping: 'Đang hoàn tiền', stopped: 'Đã dừng' },
    hints: { setup: 'Chuẩn bị ví sao chép, tác nhân giao dịch và sự đồng ý của bạn trong Cài đặt.', needs_deposit: 'Nạp USDC từ ví chính để bắt đầu sao chép.', funding: 'Khoản nạp đang được ký và gửi.', awaiting_credit: 'Đã gửi khoản nạp; đang chờ Hyperliquid ghi có.', starting: 'Đã nạp. Sao chép sẽ bắt đầu sau vài giây.', active: 'Đang sao chép giao dịch của trader trên Hyperliquid testnet.', paused: 'Giao dịch mới đang tạm dừng.', stopping: 'Đang đóng vị thế, lệnh và vị thế đang được kết thúc.', sweeping: 'Không còn vị thế. Hoàn tiền về ví chính để kết thúc.', stopped: 'Lần sao chép này đã kết thúc.' },
    equity: 'Tài sản', withdrawable: 'Có thể rút', positions: 'Vị thế', noPositions: 'Không có vị thế mở', size: 'Khối lượng', entry: 'Giá vào', pnl: 'Lãi/lỗ chưa thực hiện',
    close: 'Đóng', closing: 'Đang đóng…', setup: 'Mở thiết lập', deposit: 'Nạp tiền', withdraw: 'Rút tiền nhàn rỗi', amount: 'Số tiền (USDC)', withdrawConfirm: 'Ký và rút',
    returnAll: 'Hoàn toàn bộ về ví chính', consent: 'Ký đồng ý hủy lệnh', consentHint: 'Khi dừng đã phát hiện lệnh đang mở. Ví chính ký một sự đồng ý để Orbie chỉ hủy các lệnh đó.',
    refusal: 'Tín hiệu bị bỏ qua gần nhất: {reason}', priceDeviation: 'giá chênh quá xa giá khớp của trader', transfer: '{direction} · {status}: {amount} USDC', transferDirection: { to_account: 'Nạp tiền', to_main: 'Hoàn về ví chính' }, transferStatus: { prepared: 'đang chờ gửi', unknown: 'đang xác nhận', accepted: 'đã gửi, chờ ghi có' }, unobserved: 'Chưa đọc được số dư.',
    error: 'Thao tác chưa hoàn tất. Kiểm tra lần sao chép và thử lại.', busy: 'Đang xử lý…', cancelReturn: 'Hủy lần chuyển về này', autoReturning: 'Đang tự động hoàn trả', autoReturningHint: 'Không còn vị thế. Tiền đang tự động về ví chính của bạn, không cần ký.', returned: 'Đã hoàn trả {amount} USDC về ví chính' },
  es: { ui: { amountPlaceholder: "Introduce un importe", maxWithdrawable: "Hasta {amount}", all: "Todo", transferPending: "Transferencia en curso; podrás retirar de nuevo cuando termine", details: "Detalles", copyAddress: "Copiar dirección", withdrawTitle: "Confirmar retiro", returnTitle: "Confirmar devolución de todo", stopTitle: "Confirmar detención", amountRow: "Importe", allAmount: "Todo (unos {amount})", destination: "Destino", mainWallet: "Tu billetera principal", network: "Red", eta: "Tiempo estimado", etaValue: "Alrededor de 1 minuto", confirmWithdraw: "Confirmar retiro", confirmReturn: "Confirmar devolución", confirmStop: "Confirmar detención", cancel: "Cancelar" },
    title: 'Copias en testnet', testnet: 'Testnet', mainnetLeader: 'Trader de mainnet', testnetLeader: 'Trader de testnet',
    stages: { setup: 'Completa la configuración', needs_deposit: 'Requiere depósito', funding: 'Depositando', awaiting_credit: 'Esperando acreditación', starting: 'Iniciando', active: 'Copiando', paused: 'En pausa', stopping: 'Deteniendo', sweeping: 'Devolviendo fondos', stopped: 'Detenida' },
    hints: { setup: 'Prepara la billetera de la copia, su agente de trading y tu consentimiento en Configuración.', needs_deposit: 'Deposita USDC desde tu billetera principal para empezar a copiar.', funding: 'Tu depósito se está firmando y enviando.', awaiting_credit: 'Depósito enviado; esperando que Hyperliquid lo acredite.', starting: 'Con fondos. La copia empieza en segundos.', active: 'Copiando las operaciones del trader en la testnet de Hyperliquid.', paused: 'Las nuevas operaciones están en pausa.', stopping: 'Cerrando posiciones; se están finalizando órdenes y posiciones.', sweeping: 'Sin posiciones. Devuelve los fondos a tu billetera principal para terminar.', stopped: 'Esta copia terminó.' },
    equity: 'Patrimonio', withdrawable: 'Retirable', positions: 'Posiciones', noPositions: 'Sin posiciones abiertas', size: 'Tamaño', entry: 'Entrada', pnl: 'PnL no realizado',
    close: 'Cerrar', closing: 'Cerrando…', setup: 'Abrir configuración', deposit: 'Depositar', withdraw: 'Retirar fondos inactivos', amount: 'Monto (USDC)', withdrawConfirm: 'Firmar y retirar',
    returnAll: 'Devolver todo a la billetera principal', consent: 'Firmar consentimiento para cancelar órdenes', consentHint: 'Al detener se encontraron órdenes abiertas. Tu billetera principal firma un consentimiento para que Orbie cancele solo esas órdenes.',
    refusal: 'Última señal omitida: {reason}', priceDeviation: 'precio demasiado alejado del de la operación del trader', transfer: '{direction} · {status}: {amount} USDC', transferDirection: { to_account: 'Depósito', to_main: 'Devolución a la billetera principal' }, transferStatus: { prepared: 'esperando envío', unknown: 'confirmándose', accepted: 'enviado, esperando acreditación' }, unobserved: 'Aún no se leyeron los saldos.',
    error: 'La acción no se completó. Revisa la copia e inténtalo de nuevo.', busy: 'Procesando…', cancelReturn: 'Cancelar esta devolución', autoReturning: 'Devolviendo automáticamente', autoReturningHint: 'Sin posiciones. Los fondos vuelven solos a tu billetera principal; no hay nada que firmar.', returned: 'Se devolvieron {amount} USDC a tu billetera principal' },
  pt: { ui: { amountPlaceholder: "Digite o valor", maxWithdrawable: "Até {amount}", all: "Tudo", transferPending: "Transferência em andamento; você poderá sacar de novo quando terminar", details: "Detalhes", copyAddress: "Copiar endereço", withdrawTitle: "Confirmar saque", returnTitle: "Confirmar devolução de tudo", stopTitle: "Confirmar parada", amountRow: "Valor", allAmount: "Tudo (cerca de {amount})", destination: "Destino", mainWallet: "Sua carteira principal", network: "Rede", eta: "Tempo estimado", etaValue: "Cerca de 1 minuto", confirmWithdraw: "Confirmar saque", confirmReturn: "Confirmar devolução", confirmStop: "Confirmar parada", cancel: "Cancelar" },
    title: 'Cópias na testnet', testnet: 'Testnet', mainnetLeader: 'Trader da mainnet', testnetLeader: 'Trader da testnet',
    stages: { setup: 'Concluir configuração', needs_deposit: 'Requer depósito', funding: 'Depositando', awaiting_credit: 'Aguardando crédito', starting: 'Iniciando', active: 'Copiando', paused: 'Pausada', stopping: 'Parando', sweeping: 'Devolvendo fundos', stopped: 'Parada' },
    hints: { setup: 'Prepare a carteira da cópia, o agente de trading e o seu consentimento em Configurações.', needs_deposit: 'Deposite USDC da carteira principal para começar a copiar.', funding: 'Seu depósito está sendo assinado e enviado.', awaiting_credit: 'Depósito enviado; aguardando o crédito na Hyperliquid.', starting: 'Com fundos. A cópia começa em segundos.', active: 'Copiando as operações do trader na testnet da Hyperliquid.', paused: 'Novas operações estão pausadas.', stopping: 'Fechando posições; ordens e posições estão sendo encerradas.', sweeping: 'Sem posições. Devolva os fundos à carteira principal para concluir.', stopped: 'Esta cópia terminou.' },
    equity: 'Patrimônio', withdrawable: 'Sacável', positions: 'Posições', noPositions: 'Nenhuma posição aberta', size: 'Tamanho', entry: 'Entrada', pnl: 'PnL não realizado',
    close: 'Fechar', closing: 'Fechando…', setup: 'Abrir configurações', deposit: 'Depositar', withdraw: 'Sacar fundos ociosos', amount: 'Valor (USDC)', withdrawConfirm: 'Assinar e sacar',
    returnAll: 'Devolver tudo à carteira principal', consent: 'Assinar consentimento para cancelar ordens', consentHint: 'Ao parar foram encontradas ordens abertas. Sua carteira principal assina um consentimento para que a Orbie cancele apenas essas ordens.',
    refusal: 'Último sinal ignorado: {reason}', priceDeviation: 'preço muito distante do preço da operação do trader', transfer: '{direction} · {status}: {amount} USDC', transferDirection: { to_account: 'Depósito', to_main: 'Devolução à carteira principal' }, transferStatus: { prepared: 'aguardando envio', unknown: 'em confirmação', accepted: 'enviado, aguardando crédito' }, unobserved: 'Saldos ainda não lidos.',
    error: 'A ação não foi concluída. Verifique a cópia e tente novamente.', busy: 'Processando…', cancelReturn: 'Cancelar esta devolução', autoReturning: 'A devolver automaticamente', autoReturningHint: 'Sem posições. Os fundos estão a voltar sozinhos para a sua carteira principal; não há nada a assinar.', returned: '{amount} USDC devolvidos à sua carteira principal' },
  id: { ui: { amountPlaceholder: "Masukkan jumlah", maxWithdrawable: "Maks. {amount}", all: "Semua", transferPending: "Transfer sedang diproses; kamu bisa menarik lagi setelah selesai", details: "Detail", copyAddress: "Salin alamat", withdrawTitle: "Konfirmasi penarikan", returnTitle: "Konfirmasi pengembalian semua dana", stopTitle: "Konfirmasi penghentian", amountRow: "Jumlah", allAmount: "Semua (sekitar {amount})", destination: "Tujuan", mainWallet: "Dompet utama kamu", network: "Jaringan", eta: "Perkiraan waktu", etaValue: "Sekitar 1 menit", confirmWithdraw: "Konfirmasi penarikan", confirmReturn: "Konfirmasi pengembalian", confirmStop: "Konfirmasi penghentian", cancel: "Batal" },
    title: 'Salinan testnet', testnet: 'Testnet', mainnetLeader: 'Trader mainnet', testnetLeader: 'Trader testnet',
    stages: { setup: 'Selesaikan penyiapan', needs_deposit: 'Perlu deposit', funding: 'Sedang deposit', awaiting_credit: 'Menunggu kredit', starting: 'Segera mulai', active: 'Menyalin', paused: 'Dijeda', stopping: 'Menghentikan', sweeping: 'Mengembalikan dana', stopped: 'Dihentikan' },
    hints: { setup: 'Siapkan dompet salinan, agen trading, dan persetujuan Anda di Pengaturan.', needs_deposit: 'Deposit USDC dari dompet utama untuk mulai menyalin.', funding: 'Deposit Anda sedang ditandatangani dan dikirim.', awaiting_credit: 'Deposit terkirim; menunggu Hyperliquid mengkreditkannya.', starting: 'Dana masuk. Penyalinan dimulai dalam beberapa detik.', active: 'Menyalin trading trader di testnet Hyperliquid.', paused: 'Trading baru dijeda.', stopping: 'Menutup posisi; order dan posisi sedang diselesaikan.', sweeping: 'Tanpa posisi. Kembalikan dana ke dompet utama untuk menyelesaikan.', stopped: 'Salinan ini telah berakhir.' },
    equity: 'Ekuitas', withdrawable: 'Dapat ditarik', positions: 'Posisi', noPositions: 'Tidak ada posisi terbuka', size: 'Ukuran', entry: 'Harga masuk', pnl: 'PnL belum terealisasi',
    close: 'Tutup', closing: 'Menutup…', setup: 'Buka pengaturan', deposit: 'Deposit', withdraw: 'Tarik dana menganggur', amount: 'Jumlah (USDC)', withdrawConfirm: 'Tandatangani dan tarik',
    returnAll: 'Kembalikan semua ke dompet utama', consent: 'Tandatangani persetujuan pembatalan order', consentHint: 'Saat menghentikan ditemukan order terbuka. Dompet utama menandatangani persetujuan agar Orbie hanya membatalkan order tersebut.',
    refusal: 'Sinyal terakhir yang dilewati: {reason}', priceDeviation: 'harga terlalu jauh dari harga eksekusi trader', transfer: '{direction} · {status}: {amount} USDC', transferDirection: { to_account: 'Setoran', to_main: 'Kembali ke dompet utama' }, transferStatus: { prepared: 'menunggu dikirim', unknown: 'sedang dikonfirmasi', accepted: 'terkirim, menunggu masuk' }, unobserved: 'Saldo belum terbaca.',
    error: 'Tindakan belum selesai. Periksa salinan lalu coba lagi.', busy: 'Memproses…', cancelReturn: 'Batalkan pengembalian ini', autoReturning: 'Dikembalikan otomatis', autoReturningHint: 'Tidak ada posisi. Dana sedang kembali otomatis ke dompet utama kamu; tidak perlu tanda tangan.', returned: '{amount} USDC dikembalikan ke dompet utama' },
};

/** A mainnet copy's words for the keys that name the network: 正式, and
 * 測試網 nowhere (a testnet deployment keeps the base text). Locales
 * without their own fall back to English for these keys. */
type MainnetCopiesText = Pick<LiveCopiesText, 'title' | 'testnet'> & { active: string };
const mainnetCopies: Partial<Record<Locale, MainnetCopiesText>> = {
  en: { title: 'Live copies', testnet: 'Live', active: 'Copying the leader’s trades on Hyperliquid with real funds.' },
  'zh-TW': { title: '正式跟單', testnet: '正式', active: '正在 Hyperliquid 以真實資金跟隨交易員的交易。' },
  'zh-CN': { title: '正式跟单', testnet: '正式', active: '正在 Hyperliquid 以真实资金跟随交易员的交易。' },
};
/** The copy texts for a copy's network (`item.network`). */
export function liveCopiesText(locale: Locale, network: 'testnet' | 'mainnet' | null | undefined): LiveCopiesText {
  const base = liveCopiesMessages[locale];
  if (network !== 'mainnet') return base;
  const mainnet = mainnetCopies[locale] ?? mainnetCopies.en!;
  return { ...base, title: mainnet.title, testnet: mainnet.testnet, hints: { ...base.hints, active: mainnet.active } };
}
