-- One network per deployment (2026-10-07): a deployment executes actual copies on HYPERLIQUID_NETWORK, testnet or mainnet.
-- Every check that pinned network = 'testnet' now accepts either network, and an actual copy records its network
-- (copy_strategies.network; every existing copy is a testnet one, the column's default), so the same trader can be
-- copied once per network. Additive: every existing row passes and keeps its meaning.
ALTER TABLE "copy_account_mode_operations" DROP CONSTRAINT "copy_account_modes_states_check";--> statement-breakpoint
ALTER TABLE "copy_follower_observation_budget" DROP CONSTRAINT "copy_follower_observation_budget_network_check";--> statement-breakpoint
ALTER TABLE "copy_follower_observations" DROP CONSTRAINT "copy_follower_observations_identity_check";--> statement-breakpoint
ALTER TABLE "copy_live_builder_approvals" DROP CONSTRAINT "copy_live_builder_approvals_check";--> statement-breakpoint
ALTER TABLE "copy_live_execution_evidence" DROP CONSTRAINT "copy_live_evidence_identity_check";--> statement-breakpoint
ALTER TABLE "copy_live_mandates" DROP CONSTRAINT "copy_live_mandates_network_check";--> statement-breakpoint
ALTER TABLE "copy_live_position_baselines" DROP CONSTRAINT "copy_live_baseline_identity_check";--> statement-breakpoint
ALTER TABLE "copy_live_risk_reservations" DROP CONSTRAINT "copy_live_risk_reservations_identity_check";--> statement-breakpoint
ALTER TABLE "copy_live_stop_operations" DROP CONSTRAINT "copy_live_stops_identity_check";--> statement-breakpoint
DROP INDEX "copy_strategies_live_uq";--> statement-breakpoint
ALTER TABLE "copy_strategies" ADD COLUMN "network" text DEFAULT 'testnet' NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "copy_strategies_live_uq" ON "copy_strategies" USING btree ("user_id","chain","leader_address","mode","network") WHERE status <> 'stopped';--> statement-breakpoint
ALTER TABLE "copy_account_mode_operations" ADD CONSTRAINT "copy_account_modes_states_check" CHECK ("copy_account_mode_operations"."network" in ('testnet','mainnet') and "copy_account_mode_operations"."target" = 'disabled' and "copy_account_mode_operations"."revision" >= 1);--> statement-breakpoint
ALTER TABLE "copy_follower_observation_budget" ADD CONSTRAINT "copy_follower_observation_budget_network_check" CHECK ("copy_follower_observation_budget"."network" in ('testnet','mainnet'));--> statement-breakpoint
ALTER TABLE "copy_follower_observations" ADD CONSTRAINT "copy_follower_observations_identity_check" CHECK ("copy_follower_observations"."network" in ('testnet','mainnet') and "copy_follower_observations"."account_address" ~ '^0x[0-9a-f]{40}$' and "copy_follower_observations"."account_address" <> '0x0000000000000000000000000000000000000000' and "copy_follower_observations"."source_digest" ~ '^[0-9a-f]{64}$' and "copy_follower_observations"."producer_version" = 1 and jsonb_typeof("copy_follower_observations"."snapshot") = 'object');--> statement-breakpoint
ALTER TABLE "copy_live_builder_approvals" ADD CONSTRAINT "copy_live_builder_approvals_check" CHECK ("copy_live_builder_approvals"."network" in ('testnet','mainnet') and "copy_live_builder_approvals"."state" in ('prepared', 'unknown', 'accepted', 'rejected', 'approved') and "copy_live_builder_approvals"."max_fee_tenths_bps" between 1 and 100 and "copy_live_builder_approvals"."account_address" ~ '^0x[0-9a-f]{40}$' and "copy_live_builder_approvals"."builder_address" ~ '^0x[0-9a-f]{40}$' and "copy_live_builder_approvals"."nonce" > 0 and ("copy_live_builder_approvals"."state" = 'prepared' or "copy_live_builder_approvals"."attempted_at" is not null));--> statement-breakpoint
ALTER TABLE "copy_live_execution_evidence" ADD CONSTRAINT "copy_live_evidence_identity_check" CHECK ("copy_live_execution_evidence"."network" in ('testnet','mainnet') and "copy_live_execution_evidence"."account_address" ~ '^0x[0-9a-f]{40}$' and "copy_live_execution_evidence"."account_address" <> '0x0000000000000000000000000000000000000000' and "copy_live_execution_evidence"."cloid" ~ '^0x[0-9a-f]{32}$' and "copy_live_execution_evidence"."fingerprint" ~ '^[0-9a-f]{64}$' and "copy_live_execution_evidence"."nonce" > 0 and "copy_live_execution_evidence"."nonce" <= 9007199254740991 and "copy_live_execution_evidence"."revision" > 0 and ("copy_live_execution_evidence"."exchange_order_id" is null or ("copy_live_execution_evidence"."exchange_order_id" ~ '^[1-9][0-9]{0,19}$' and "copy_live_execution_evidence"."exchange_order_id"::numeric <= 18446744073709551615)));--> statement-breakpoint
ALTER TABLE "copy_live_mandates" ADD CONSTRAINT "copy_live_mandates_network_check" CHECK ("copy_live_mandates"."network" in ('testnet','mainnet') and "copy_live_mandates"."source_network" in ('testnet','mainnet'));--> statement-breakpoint
ALTER TABLE "copy_live_position_baselines" ADD CONSTRAINT "copy_live_baseline_identity_check" CHECK ("copy_live_position_baselines"."network" in ('testnet','mainnet') and "copy_live_position_baselines"."account_address" ~ '^0x[0-9a-f]{40}$' and "copy_live_position_baselines"."account_address" <> '0x0000000000000000000000000000000000000000' and "copy_live_position_baselines"."producer_version" = 1);--> statement-breakpoint
ALTER TABLE "copy_live_risk_reservations" ADD CONSTRAINT "copy_live_risk_reservations_identity_check" CHECK ("copy_live_risk_reservations"."network" in ('testnet','mainnet') and "copy_live_risk_reservations"."account_address" ~ '^0x[0-9a-f]{40}$' and "copy_live_risk_reservations"."account_address" <> '0x0000000000000000000000000000000000000000' and "copy_live_risk_reservations"."cloid" ~ '^0x[0-9a-f]{32}$' and "copy_live_risk_reservations"."fingerprint" ~ '^[0-9a-f]{64}$' and "copy_live_risk_reservations"."source_digest" ~ '^[0-9a-f]{64}$' and length("copy_live_risk_reservations"."wallet_id") between 1 and 128 and "copy_live_risk_reservations"."asset" >= 0);--> statement-breakpoint
ALTER TABLE "copy_live_stop_operations" ADD CONSTRAINT "copy_live_stops_identity_check" CHECK ("copy_live_stop_operations"."network" in ('testnet','mainnet') and "copy_live_stop_operations"."account_address" ~ '^0x[0-9a-f]{40}$' and "copy_live_stop_operations"."owner_address" ~ '^0x[0-9a-f]{40}$' and "copy_live_stop_operations"."account_address" <> '0x0000000000000000000000000000000000000000' and "copy_live_stop_operations"."owner_address" <> '0x0000000000000000000000000000000000000000' and "copy_live_stop_operations"."owner_address" <> "copy_live_stop_operations"."account_address" and length("copy_live_stop_operations"."owner_privy_user_id") between 1 and 128 and length("copy_live_stop_operations"."account_wallet_id") between 1 and 128 and length("copy_live_stop_operations"."account_owner_quorum_id") between 1 and 128);--> statement-breakpoint
ALTER TABLE "copy_strategies" ADD CONSTRAINT "copy_strategies_network_check" CHECK ("copy_strategies"."network" in ('testnet', 'mainnet'));