import{it,expect}from'vitest';import{readFileSync}from'node:fs';import{example}from'./copy-fixed-claim-proof-test-utils.js';import{validateFixedClaimRefusal as validate}from'./copy-fixed-claim-proof-test-utils.js';import{proofTools}from'./copy-fixed-claim-proof-test-utils.js';import{fixedClaimEvidenceQuery}from'../../../scripts/copy-harness/fixed-claim-proof.mjs';
it('real decoders/certificate and independent SDK accept distinct original quorum, NOT user DID',()=>{const x=example();expect(x.mandate.intent.ownerPrivyUserId).toBe('did:owner');expect(x.generation.manifest.journals[0].journal.record.authorization.privyOwnerId).toBe('quorum:agent-owner');expect(proofTools.decodeLiveCopyMandate(x.mandate)).not.toHaveProperty('agentOwnerQuorumId');expect(validate(x)).not.toBeNull()});
for(const [group,key,value]of [['account','ownerQuorumId','foreign'],['account','privyUserId','foreign'],['account','privyWalletId','foreign'],['account','id','foreign'],['account','userId',2],['account','network','mainnet'],['setup','id','later-generation'],['setup','revision',2],['setup','agentOwnerQuorumId','foreign'],['setup','accountOwnerQuorumId','foreign'],['setup','accountWalletId','foreign'],['setup','authorizationId','foreign'],['setup','policyFingerprint','b'.repeat(64)],['setup','workerQuorumId','foreign'],['wallet','id','foreign'],['wallet','privyWalletId','foreign'],['wallet','privyOwnerId','did:owner'],['wallet','network','mainnet'],['wallet','signerAddress','foreign']])it(group+'.'+key+' exact binding rejects',()=>{const x=example();(x.authorizationBinding as any)[group][key]=value;expect(validate(x)).toBeNull()});
it('all three quorum fields spoofed to DID still reject original settled authorization',()=>{const x=example();x.authorizationBinding.account.ownerQuorumId='did:owner';x.authorizationBinding.setup.accountOwnerQuorumId='did:owner';x.authorizationBinding.setup.agentOwnerQuorumId='did:owner';x.authorizationBinding.wallet.privyOwnerId='did:owner';expect(validate(x)).toBeNull()});
for(const b of [null,{}, {setup:{},wallet:{},account:{}}])it('missing binding fails closed',()=>{const x=example();(x as any).authorizationBinding=b;expect(validate(x)).toBeNull()});
it('historical retired wallet/blocked setup not required currently active',()=>{const x=example();(x.authorizationBinding.setup as any).state='revoked';expect(validate(x)).not.toBeNull()});
it('missing independent SDK fill remains false with exact quorum',()=>{const x=example();x.sdk.fills=[];expect(validate(x)).toBeNull()});
it('mandate consent digest/fingerprint untouched',()=>{const x=example(),before=JSON.stringify(x.mandate);validate(x);expect(JSON.stringify(x.mandate)).toBe(before)});
it('new SQL aliases actual production columns exist without DB access',()=>{const schema=readFileSync(new URL('../../../packages/shared/src/schema/db.ts',import.meta.url),'utf8');const sql=fixedClaimEvidenceQuery({id:'d',mandateId:'m',userId:14,sourceFillId:'s',state:'refused',leg:'open',reason:'fixed_trade_already_claimed'},{network:'testnet',leaderNetwork:'testnet',leader:'0x'+'1'.repeat(40),follower:'0x'+'2'.repeat(40)});for(const [alias,table]of [['ag','copy_agent_setups'],['w','copy_execution_wallets']]){const body=new RegExp('pgTable\\("'+table+'", \\{([\\s\\S]*?)\\n\\},').exec(schema)?.[1];expect(body).toBeTruthy();if(!sql)throw Error('missing exact evidence query');for(const m of sql.matchAll(new RegExp('\\b'+alias+'\\.([a-z_]+)\\b','g')))expect(body).toContain('"'+m[1]+'"')}});
