import {Pool} from 'pg';
import {eq,sql} from 'drizzle-orm';
import {beforeAll,beforeEach,afterAll,describe,it,expect,vi} from 'vitest';
import {copyLiveExecutions,copyLiveRiskReservations,copyLiveIntentProvenance,copyLiveSignalLegs,copyLiveReductionCarry,copyLiveSourceFills,copyLiveSourceStreams,copyLiveMandates,copyFollowerReceipts,copyFollowerScans,copyLiveExecutionEvidence,copyStrategies,users,copyWalletAuthorizations,copyWalletAuthorizationEvents,copyExecutionAccounts,copyExecutionWallets,copyAgentSetups} from '@trading-dashboard/shared/database';
import {CopyWalletRepository} from '../src/copy/copy-wallet.repository.js';
import {CopyAgentRepository} from '../src/copy/copy-agent.repository.js';
import {PostgresLiveUnattemptedRecovery} from '../src/copy/live/postgres-live-unattempted-recovery.js';
import {PostgresLivePreparation} from '../src/copy/live/postgres-live-preparation.js';
import {PostgresLiveSettlement} from '../src/copy/live/postgres-live-settlement.js';
import {CopyFollowerLedger} from '../src/copy/live/copy-follower-ledger.js';
import {UnitOfWork} from '../src/db/unit-of-work.js';
import {Dec} from '../src/common/decimal/dec.js';
import {parseLiveOrderEvidence,parseLiveIocAcknowledgement,captureLiveOrderIdentity} from '../src/copy/live/live-order-evidence.js';
import {PostgresLiveRiskScope,type LiveRiskDatabaseSession} from '../src/copy/live/postgres-live-risk-scope.js';
import {HyperliquidLiveAccountObserver} from '../src/copy/live/live-account-observer.js';
import {HyperliquidLiveMarketResolver} from '../src/copy/live/live-market-resolver.js';
import {HyperliquidLiveRiskProvider} from '../src/copy/live/live-risk-provider.js';
import {planLiveReservation} from '../src/copy/live/live-risk-reservation.js';
import {loadLiveGenerationManifest} from '../src/copy/live/postgres-live-generation-manifest.js';
import {projectLiveGenerationPositions} from '../src/copy/live/copy-live-generation-projection.js';
import {decodeLiveUnattemptedRelease,captureLiveUnattemptedRelease} from '../src/copy/live/live-unattempted-release.js';
import {liveSourceDigest,parseLiveSourceFill} from '../src/copy/live/copy-live-source-evidence.js';
import {digest} from '../src/copy/copy-live-mandate-evidence.js';
import {preparationFixture} from './copy-live-preparation-test-utils.js';
import {now} from './copy-live-risk-test-utils.js';
import {getTestDb,closeTestDb,insertUser,type TestDb} from './db-test-utils.js';
let db:TestDb,pool:Pool,clock:number,scope:PostgresLiveRiskScope,seed:Awaited<ReturnType<typeof preparationFixture>>,recovery:PostgresLiveUnattemptedRecovery,prepared:Awaited<ReturnType<PostgresLivePreparation['prepare']>>,prep:PostgresLivePreparation,observer:HyperliquidLiveAccountObserver,position:string;
beforeAll(()=>{db=getTestDb();pool=new Pool({connectionString:process.env.TEST_DATABASE_URL,max:1});});
afterAll(async()=>{await pool.end();await closeTestDb();});
const identity=()=>({userId:1,network:'testnet' as const,accountAddress:seed.f.identity.accountAddress,source:{network:'testnet' as const,leaderAddress:seed.consent.leaderAddress}});
function snapshot(){const value=structuredClone(seed.f.accountSource.snapshot),p=Dec.from(position),notional=p.abs().mul(100).toString(),margin=p.abs().mul(10).toString();Object.assign(value,{observedAt:clock,completedAt:clock,totalMarginUsed:margin,exposureUsd:notional});Object.assign(value.coverage,{earliestProviderTime:clock});value.dexes.forEach(d=>{Object.assign(d,{providerTime:clock,marginUsed:margin,exposureUsd:notional,crossMarginUsed:margin,crossExposureUsd:notional});});if(!p.isZero)(value.positions as unknown[]).push({coin:'BTC',dex:'',asset:0,sizeDecimals:2,size:position,entryPrice:'100',positionValue:notional,unrealizedPnl:'0',marginUsed:margin,leverage:10,leverageType:'cross',maxLeverage:20,fundingSinceOpen:'0',fundingSinceChange:'0'});return value;}
async function setup(rawExtra?:string,longExpiry=false){
 seed=await preparationFixture(db);clock=now;position='0';scope=new PostgresLiveRiskScope(pool,()=>clock);recovery=new PostgresLiveUnattemptedRecovery(()=>clock);
 if(rawExtra){const fill=parseLiveSourceFill({...seed.fill.raw,providerExtra:rawExtra},{network:'testnet',leaderAddress:seed.consent.leaderAddress,from:now-1000,to:now,receivedAt:now,kind:'fills'});await db.update(copyLiveSourceFills).set({raw:fill.raw,sourceDigest:fill.sourceDigest});seed.fill=fill;}
 if(longExpiry){const expiresAt=now+86400000;seed.consent={...seed.consent,expiresAt};await db.update(copyLiveMandates).set({expiresAt:new Date(expiresAt),intent:seed.consent,intentDigest:digest(seed.consent)});await db.update(copyWalletAuthorizations).set({expiresAt:new Date(expiresAt)});await db.update(copyAgentSetups).set({expiresAt:new Date(expiresAt)});}
 const fetcher=vi.fn<typeof fetch>(async()=>{throw Error('No real provider requests');}),acquire=async()=>{};
 observer=new HyperliquidLiveAccountObserver('testnet',acquire,fetcher,()=>clock);const resolver=new HyperliquidLiveMarketResolver('testnet',acquire,fetcher,()=>clock),provider=new HyperliquidLiveRiskProvider('testnet',acquire,fetcher,()=>clock);
 vi.spyOn(observer,'observe').mockImplementation(async()=>snapshot());vi.spyOn(resolver,'resolve').mockImplementation(async()=>({...seed.f.market,observedAt:clock}));
 vi.spyOn(provider,'observe').mockImplementation(async()=>({network:'testnet',accountAddress:seed.f.identity.accountAddress,coin:'BTC',dex:'',asset:0,market:{...seed.f.market,observedAt:clock},earliestObservedAt:clock,completedAt:clock,sourceDigest:'a'.repeat(64),quote:{...seed.f.quote,market:{...seed.f.market,observedAt:clock},observedAt:clock},leverageProofs:seed.f.leverageProofs.map(l=>({...l,observedAt:clock})),fees:{...seed.f.fees,observedAt:clock}} as never));
 prep=new PostgresLivePreparation(observer,resolver,provider,{slippageBps:'50',extraRiskBufferBps:'0',restingOrderBuilderFeeCapTenthsBps:100},()=>clock);
 prepared=await scope.run(identity(),(_s,session)=>prep.prepare(session,{accountId:'account',mandateId:'mandate',sourceFillId:seed.fill.id,leg:'open'}));
 const payload=planLiveReservation({now:clock,identity:seed.f.identity,localSource:{...seed.f.localSource,checkedAt:clock},intent:prepared.intent,action:prepared.record.action,market:prepared.intent.market!,quote:{...seed.f.quote,market:prepared.intent.market!,observedAt:clock},leverage:{...seed.f.leverageProofs[0]!,observedAt:clock},fees:{...seed.f.fees,observedAt:clock},policy:seed.f.policy,expiresAt:prepared.record.expiresAfter});
 await db.insert(copyLiveRiskReservations).values({...payload,cloid:prepared.intent.cloid,coin:'BTC',dex:'',asset:0,payload:payload as never,state:'held',createdAt:new Date(payload.createdAt),expiresAt:new Date(payload.expiresAt),updatedAt:new Date(clock)});
 clock=prepared.record.expiresAfter+1;
}
beforeEach(()=>setup());
const release=(revision=1)=>scope.run(identity(),(_s,session)=>recovery.releaseExpired(session,{accountId:'account',key:prepared.record.key,expectedReservationRevision:revision}));
async function financialRows(){return {journal:await db.select().from(copyLiveExecutions),reservation:await db.select().from(copyLiveRiskReservations),leg:await db.select().from(copyLiveSignalLegs),carry:await db.select().from(copyLiveReductionCarry)};}
async function revokeOriginalGrant(){const repository=new CopyWalletRepository(db);await db.transaction(async tx=>{const row=await repository.lockedGrant(tx,1,'grant');if(!row)throw Error('Missing original owned grant');const at=new Date(clock),grant=await repository.revokeGrant(tx,row.grant.id,row.grant.version+1,at);await repository.recordRevocation(tx,{id:'actual-revocation',authorizationId:grant!.id,userId:1,version:grant!.version,action:'revoked',createdAt:at});});}
async function manifest(session:LiveRiskDatabaseSession){return session.read(async tx=>{const [account]=await tx.select().from(copyExecutionAccounts),[mandate]=await tx.select().from(copyLiveMandates);return loadLiveGenerationManifest(session,tx,{account,mandate} as never,{currentExecutionKey:'next-key',now:clock});});}
function project(value:unknown){return projectLiveGenerationPositions({identity:{mandateId:'mandate',mandateRevision:2,accountId:'account',userId:1,strategyId:9,network:'testnet',accountAddress:seed.f.identity.accountAddress,authorizationId:'grant',settingsDigest:seed.consent.settingsDigest,leaderAddress:seed.consent.leaderAddress,direction:'same'},manifest:value,snapshot:snapshot(),currentExecutionKey:'next-key',now:clock});}
async function laterSource(tid:number,side:'A'|'B',startPosition:string){
 clock+=20;const fill=parseLiveSourceFill({tid,oid:tid+10,time:clock-1,coin:'BTC',px:'100',sz:'1',side,startPosition},{network:'testnet',leaderAddress:seed.consent.leaderAddress,from:clock-1,to:clock,receivedAt:clock,kind:'fills'});
 await db.insert(copyLiveSourceFills).values({...fill,normalized:{...fill.normalized},providerTime:new Date(fill.providerTime),receivedAt:new Date(fill.receivedAt)});await db.update(copyLiveSourceStreams).set({coverageThrough:new Date(clock)});return fill;
}
async function actualTerminal(p:typeof prepared,oid:number,filled:string,remaining:string,status='filled'){
 const record={...p.record,state:'unknown' as const,updatedAt:clock,outcome:{state:'filled' as const,exchangeOrderId:String(oid)}};
 await db.update(copyLiveExecutions).set({state:'unknown',record,updatedAt:new Date(clock)}).where(eq(copyLiveExecutions.key,record.key));
 const payload=planLiveReservation({now:clock,identity:seed.f.identity,localSource:{...seed.f.localSource,checkedAt:clock},intent:p.intent,action:record.action,market:p.intent.market!,quote:{...seed.f.quote,market:p.intent.market!,observedAt:clock},leverage:{...seed.f.leverageProofs[0]!,observedAt:clock},fees:{...seed.f.fees,observedAt:clock},policy:seed.f.policy,expiresAt:record.expiresAfter});
 await db.insert(copyLiveRiskReservations).values({...payload,cloid:p.intent.cloid,coin:'BTC',dex:'',asset:0,payload:payload as never,state:'unknown',revision:2,attemptedAt:new Date(clock),createdAt:new Date(payload.createdAt),expiresAt:new Date(payload.expiresAt),updatedAt:new Date(clock)});
 const placed=clock;clock+=5;await new CopyFollowerLedger(db,new UnitOfWork(db)).bookFill('account',{coin:'BTC',oid,tid:100+oid,side:p.intent.side,time:clock,sz:filled,px:'100',feeToken:'USDC',fee:'0.1',builderFee:'0.02',closedPnl:'0'});
 await db.insert(copyFollowerScans).values({accountId:'account',through:clock}).onConflictDoUpdate({target:copyFollowerScans.accountId,set:{through:clock}});clock+=10;
 const evidence=parseLiveOrderEvidence({record,market:{...record.market!,observedAt:clock},raw:{status:'order',order:{status,statusTimestamp:placed+10,order:{coin:'BTC',oid,cloid:p.intent.cloid,side:p.intent.side,reduceOnly:p.intent.reduceOnly,tif:'Ioc',origSz:p.intent.size,sz:status==='filled'?'0':p.intent.size,limitPx:p.intent.limitPrice,timestamp:placed,isTrigger:false,isPositionTpsl:false,children:[]}}},checkedAt:clock,completedAt:clock,now:clock});
 const acknowledgement=status!=='filled'?parseLiveIocAcknowledgement({identity:captureLiveOrderIdentity(record,record.market!),checkedAt:placed+6,raw:{status:'ok',response:{type:'order',data:{statuses:[{filled:{oid,totalSz:filled,avgPx:'100'}}]}}}}):undefined;
 clock+=5;position=remaining;const settlement=new PostgresLiveSettlement(()=>clock);return scope.run(identity(),async(_s,session)=>{await settlement.observe(session,{accountId:'account',key:p.record.key,evidence,...(acknowledgement?{acknowledgement}:{})});return settlement.settle(session,{accountId:'account',key:p.record.key,expectedReservationRevision:2,accountSource:{...seed.f.accountSource,checkedAt:clock,snapshot:snapshot()}});});
}
describe('local expiry recovery for actual orders with no submission',()=>{
 it('atomically releases held budget, rejects original journal and skips leg while preserving carry/nonce/provenance',async()=>{
  const before=await financialRows(),p=await db.select().from(copyLiveIntentProvenance);await release();const after=await financialRows();
  expect(after.journal[0]).toMatchObject({state:'rejected',nonce:prepared.record.nonce,record:{errorCode:'unattempted_expired',unattemptedRelease:{version:1,kind:'unattempted_expired'}}});
  expect(after.reservation[0]).toMatchObject({state:'released',releaseReason:'unattempted_expired',revision:2,attemptedAt:null,exchangeOrderId:null});expect(after.leg[0]).toMatchObject({state:'skipped',revision:3});expect(after.carry).toEqual(before.carry);expect(await db.select().from(copyLiveIntentProvenance)).toEqual(p);
  expect(after.reservation[0]!.releaseEvidenceDigest).toMatch(/^[a-f0-9]{64}$/);expect(after.journal[0]!.record.outcome).toBeUndefined();expect(await db.select().from(copyLiveExecutionEvidence)).toEqual([]);
 });
 it('replays the exact retained certificate after later clock/revocation without rewriting rows',async()=>{const cert=await release(),before=await financialRows();clock+=100000;await db.update(users).set({disabledAt:new Date(clock)});await db.update(copyLiveMandates).set({state:'revoked',revision:3,updatedAt:new Date(clock)});expect(await release()).toEqual(cert);expect(await release(2)).toEqual(cert);expect(await financialRows()).toEqual(before);});
 it('allows zero-effect cleanup after owner disabled, strategy stopped, grant revoked and old settings superseded',async()=>{await db.update(users).set({disabledAt:new Date(clock)});await db.update(copyStrategies).set({status:'stopped',stoppedAt:new Date(clock),version:3});await db.update(copyLiveMandates).set({state:'revoked',revision:3,updatedAt:new Date(clock)});await db.update(copyWalletAuthorizations).set({revokedAt:new Date(clock)});await release();expect((await financialRows()).reservation[0]!.state).toBe('released');});
 it('cleans and replays after the genuine version-changing owned grant revocation writer',async()=>{await revokeOriginalGrant();expect((await db.select().from(copyWalletAuthorizations))[0]).toMatchObject({version:5,revokedAt:new Date(clock)});await db.update(users).set({disabledAt:new Date(clock)});await db.update(copyLiveMandates).set({state:'revoked',revision:3,updatedAt:new Date(clock)});const c=await release(),before=await financialRows();expect(await release(2)).toEqual(c);expect(await financialRows()).toEqual(before);});
 it('allows genuine version-changing revocation after a retained local release without changing its historical grant',async()=>{const c=await release();await revokeOriginalGrant();const before=await financialRows();expect(await release(2)).toEqual(c);expect(await financialRows()).toEqual(before);expect(c.original.journal.record.authorization).toMatchObject({version:4});});
 it('cleans after the actual expired-agent ensure writer revokes and records its original transaction timestamp',async()=>{clock=Date.now();const repository=new CopyAgentRepository(db);await db.transaction(tx=>repository.ensure(tx,1,'account',{idempotencyKey:'actual-agent-renewal-key',validForDays:1},'worker-quorum'));const [grant]=await db.select().from(copyWalletAuthorizations),[event]=await db.select().from(copyWalletAuthorizationEvents);expect(grant).toMatchObject({version:5});expect(event).toMatchObject({authorizationId:'grant',userId:1,version:5,action:'revoked'});clock=Date.now();await release();});
 it('preserves a genuine DB-ahead agent revocation and accepts only once the checked clock reaches both original times',async()=>{const actual=Date.now();vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(actual-1000);try{clock=Date.now();const repository=new CopyAgentRepository(db);await db.transaction(tx=>repository.ensure(tx,1,'account',{idempotencyKey:'actual-agent-clock-skew-key',validForDays:1},'worker'));const [grant]=await db.select().from(copyWalletAuthorizations),[event]=await db.select().from(copyWalletAuthorizationEvents);expect(event!.createdAt.getTime()).toBeGreaterThan(grant!.revokedAt!.getTime());const before=await financialRows();await expect(release()).rejects.toThrow();expect(await financialRows()).toEqual(before);clock=event!.createdAt.getTime()+1;await release();expect((await financialRows()).reservation[0]!.state).toBe('released');}finally{vi.useRealTimers();}});
 it('retains the original target identity after actual agent activation retires the old wallet',async()=>{clock=Date.now();const repository=new CopyAgentRepository(db);const fresh=await db.transaction(tx=>repository.ensure(tx,1,'account',{idempotencyKey:'actual-agent-rotation-key',validForDays:1},'worker'));const at=Date.now(),approval=await repository.transition(fresh,{state:'approval_unknown',agentWalletId:'new-agent-wallet',agentAddress:`0x${'77'.repeat(20)}`,agentOwnerQuorumId:'owner',policyId:'new-policy',policyFingerprint:'c'.repeat(64),approvalNonce:at,consentExpiresAt:new Date(at+300000),consentDigest:'d'.repeat(64),approvalAttemptedAt:new Date(at)});await db.transaction(tx=>repository.activate(tx,1,approval!,Date.now(),Date.now()));const [old]=await db.select().from(copyExecutionWallets).where(eq(copyExecutionWallets.id,'wallet-row'));expect(old!.retiredAt).toBeInstanceOf(Date);expect((await db.select().from(copyWalletAuthorizations).where(eq(copyWalletAuthorizations.id,'grant')))[0]!.version).toBe(5);clock=Date.now();await release();});
 it.each(['missing_event','wrong_owner','wrong_version','no_revoked_at','extra_version','future_event','future_revoke','before_original','changed_scopes','changed_validity'] as const)('denies unsupported revoked-version history: %s',async(kind)=>{
  await revokeOriginalGrant();if(kind==='missing_event')await db.delete(copyWalletAuthorizationEvents);if(kind==='wrong_owner'){const other=await insertUser(db,{privyUserId:'did:privy:other-event-owner'});await db.update(copyWalletAuthorizationEvents).set({userId:other.id});}if(kind==='wrong_version')await db.update(copyWalletAuthorizationEvents).set({version:6});if(kind==='no_revoked_at')await db.update(copyWalletAuthorizations).set({revokedAt:null});if(kind==='extra_version')await db.update(copyWalletAuthorizations).set({version:6});
  if(kind==='future_event')await db.update(copyWalletAuthorizationEvents).set({createdAt:new Date(clock+1)});if(kind==='future_revoke')await db.update(copyWalletAuthorizations).set({revokedAt:new Date(clock+1)});if(kind==='before_original')await db.update(copyWalletAuthorizations).set({revokedAt:new Date(now-1)});if(kind==='changed_scopes')await db.update(copyWalletAuthorizations).set({scopes:['copy:reduce']});if(kind==='changed_validity')await db.update(copyWalletAuthorizations).set({validFrom:new Date(now)});
  const before=await financialRows();await expect(release()).rejects.toThrow();expect(await financialRows()).toEqual(before);
 });
 it('unblocks generation only after independently verified local zero-effect certificate',async()=>{const before=await scope.run(identity(),(_s,session)=>manifest(session));expect(()=>project(before)).toThrow('live_generation_unproven');await release();const after=await scope.run(identity(),(_s,session)=>manifest(session));expect(project(after).positions).toEqual({});const bad=structuredClone(after);(bad.journals[0]!.journal.record as any).unattemptedRelease.checkedAt=prepared.record.expiresAfter;expect(()=>project(bad)).toThrow('live_generation_unproven');});
 it('denies a genuine oversized source witness before writing an unreadable terminal journal',async()=>{await setup('x'.repeat(20000));const before=await financialRows();await expect(release()).rejects.toThrow();expect(await financialRows()).toEqual(before);});
 it.each(['grant_version','grant_scopes','grant_valid_from','grant_expiry','setup_wallet','setup_agent','setup_owner','setup_worker','setup_policy','setup_policy_digest','owner_address'] as const)('rejects historical immutable binding drift: %s',async(field)=>{
  if(field==='grant_version')await db.update(copyWalletAuthorizations).set({version:5});if(field==='grant_scopes')await db.update(copyWalletAuthorizations).set({scopes:['copy:reduce']});if(field==='grant_valid_from')await db.update(copyWalletAuthorizations).set({validFrom:new Date(now)});if(field==='grant_expiry')await db.update(copyWalletAuthorizations).set({expiresAt:new Date(now+60001)});
  if(field==='setup_wallet')await db.update(copyAgentSetups).set({agentWalletId:'other-agent'});if(field==='setup_agent')await db.update(copyAgentSetups).set({agentAddress:`0x${'77'.repeat(20)}`});if(field==='setup_owner')await db.update(copyAgentSetups).set({agentOwnerQuorumId:'other-owner'});if(field==='setup_worker')await db.update(copyAgentSetups).set({workerQuorumId:'other-worker'});if(field==='setup_policy')await db.update(copyAgentSetups).set({policyId:'other-policy'});if(field==='setup_policy_digest')await db.update(copyAgentSetups).set({policyFingerprint:'d'.repeat(64)});
  if(field==='owner_address')await db.update(users).set({embeddedWalletAddress:`0x${'77'.repeat(20)}`});
  const before=await financialRows();await expect(release()).rejects.toThrow();expect(await financialRows()).toEqual(before);
 });
 it('allows later master verification revision changes with the same immutable wallet identity',async()=>{await db.update(copyExecutionAccounts).set({revision:2,state:'unknown'});await release();expect((await financialRows()).reservation[0]!.state).toBe('released');});
 it.each(['carry','prepared_time'] as const)('rejects rehashed historical %s after later carry advancement',async(field)=>{
  const c=structuredClone(await release()) as any;await db.update(copyLiveReductionCarry).set({carry:'0.1',revision:2,updatedAt:new Date(clock+1)});clock+=10;
  if(field==='carry')c.original.carry.carry='0.9';else{c.original.journal.updatedAt=new Date(now+1).toISOString();c.original.journal.record.updatedAt=now+1;}
  const {digest:_digest,...proof}=c;c.digest=liveSourceDigest(proof);const [j]=await db.select().from(copyLiveExecutions);await db.update(copyLiveExecutions).set({record:{...j!.record,unattemptedRelease:c}});await db.update(copyLiveRiskReservations).set({releaseEvidenceDigest:c.digest});
  const before=await financialRows();await expect(release()).rejects.toThrow();expect(await financialRows()).toEqual(before);const m=await scope.run(identity(),(_s,session)=>manifest(session));expect(()=>project(m)).toThrow('live_generation_unproven');
 });
 it.each(['expiry','nonce','source','leg_revision','carry','sizing_digest','digest','kind'] as const)('rejects retained certificate corruption: %s',async(field)=>{
  const certificate=await release(),bad=structuredClone(certificate) as {-readonly [K in keyof typeof certificate]:typeof certificate[K]},original=bad.original as any;
  if(field==='expiry')bad.checkedAt=prepared.record.expiresAfter;
  if(field==='nonce'){original.journal.nonce++;original.journal.record.nonce++;}
  if(field==='source')original.fill.raw.sz='2';
  if(field==='leg_revision')original.leg.revision++;
  if(field==='carry')original.carry.carry='0.1';
  if(field==='sizing_digest')original.provenance.sizingBasisDigest='d'.repeat(64);
  if(field==='digest')bad.digest='d'.repeat(64);if(field==='kind')(bad as any).kind='verified_settlement';
  if(!['digest','kind'].includes(field)){const {digest:_digest,...proof}=bad;bad.digest=liveSourceDigest(proof);}
  const [j]=await db.select().from(copyLiveExecutions);await db.update(copyLiveExecutions).set({record:{...j!.record,unattemptedRelease:bad}});await db.update(copyLiveRiskReservations).set({releaseEvidenceDigest:bad.digest});
  const before=await financialRows();await expect(release()).rejects.toThrow();expect(await financialRows()).toEqual(before);
  const value=await scope.run(identity(),(_s,session)=>manifest(session));expect(()=>project(value)).toThrow('live_generation_unproven');
 });
 it('bounded pure certificate decoder rejects extra fields, non-JSON and oversized local evidence',async()=>{
  const c=await release();expect(decodeLiveUnattemptedRelease(c,c.digest)).toEqual(c);
  expect(()=>decodeLiveUnattemptedRelease({...c,providerTerminal:true},c.digest)).toThrow();expect(()=>decodeLiveUnattemptedRelease({...c,checkedAt:new Date()},c.digest)).toThrow();
  const large=structuredClone(c);(large.original.journal.record as any).extra='x'.repeat(128*1024);expect(()=>decodeLiveUnattemptedRelease(large,c.digest)).toThrow();
  const input={checkedAt:c.checkedAt,original:structuredClone(c.original)};Object.defineProperty(input.original.journal.record,'signature',{value:'private',enumerable:true});expect(()=>captureLiveUnattemptedRelease(input)).toThrow();
 });
 it('replay after a later carry revision preserves that newer carry rather than restoring historical values',async()=>{const certificate=await release();await db.update(copyLiveReductionCarry).set({carry:'0.1',revision:2,updatedAt:new Date(clock+1)});clock+=10;const before=await financialRows();expect(await release()).toEqual(certificate);expect(await financialRows()).toEqual(before);});
 it('keeps the expired zero-effect proof valid after a genuine subsequent opening and partial terminal reduction advance carry',async()=>{
  await setup(undefined,true);const certificate=await release();
  const openFill=await laterSource(2,'B','0'),open=await scope.run(identity(),(_s,session)=>prep.prepare(session,{accountId:'account',mandateId:'mandate',sourceFillId:openFill.id,leg:'open'}));expect(open.intent.size).toBe('0.09');expect((await actualTerminal(open,10,'0.09','0.09')).kind).toBe('release');
  const closeFill=await laterSource(3,'A','4'),close=await scope.run(identity(),(_s,session)=>prep.prepare(session,{accountId:'account',mandateId:'mandate',sourceFillId:closeFill.id,leg:'close'}));expect(close.intent.size).toBe('0.02');expect((await actualTerminal(close,11,'0.01','0.08','canceled')).kind).toBe('release');
  expect((await db.select().from(copyLiveReductionCarry))[0]).toMatchObject({carry:'0.0125',revision:2});const before=await financialRows();expect(await release()).toEqual(certificate);expect(await financialRows()).toEqual(before);
  expect(project(await scope.run(identity(),(_s,session)=>manifest(session))).positions).toEqual({BTC:'0.08'});
 });
 it('rolls all writes back if completion clock no longer proves the checked original expiry',async()=>{
  const before=await financialRows(),privateRecovery=recovery as unknown as {fresh(at:number):void},original=privateRecovery.fresh.bind(recovery);
  const fence=vi.spyOn(privateRecovery,'fresh').mockImplementation(at=>{clock=now;original(at);});
  try{await expect(release()).rejects.toThrow();expect(await financialRows()).toEqual(before);}finally{fence.mockRestore();}
 });
 it.each(['not_expired','equal_expiry','submitting','unknown','resting','attempt','wrong_revision','foreign_owner','source_scope_missing','source_scope_wrong','source_digest','source_raw','provenance','carry','leg','evidence','receipt'] as const)('rejects %s without any financial-state changes',async(reason)=>{
  if(reason==='not_expired')clock=prepared.record.expiresAfter-1;if(reason==='equal_expiry')clock=prepared.record.expiresAfter;
  if(['submitting','unknown','resting'].includes(reason)){const state=reason as 'submitting'|'unknown'|'resting';await db.update(copyLiveExecutions).set({state,record:{...prepared.record,state,updatedAt:clock},updatedAt:new Date(clock)});}
  if(['unknown','resting','attempt'].includes(reason))await db.update(copyLiveRiskReservations).set({state:reason==='resting'?'resting':'unknown',attemptedAt:new Date(now),exchangeOrderId:reason==='resting'?'10':null});
  if(reason==='source_digest')await db.update(copyLiveSourceFills).set({sourceDigest:'d'.repeat(64)});
  if(reason==='source_raw')await db.update(copyLiveSourceFills).set({raw:{...seed.fill.raw,sz:'2'}});
  if(reason==='provenance')await db.update(copyLiveIntentProvenance).set({fingerprint:'d'.repeat(64)});
  if(reason==='carry')await db.update(copyLiveReductionCarry).set({carry:'0.1'});
  if(reason==='leg')await db.update(copyLiveSignalLegs).set({sign:-1});
  if(reason==='evidence')await db.insert(copyLiveExecutionEvidence).values({key:prepared.record.key,accountId:'account',userId:1,strategyId:9,network:'testnet',accountAddress:prepared.intent.accountAddress,cloid:prepared.intent.cloid,fingerprint:prepared.record.fingerprint,nonce:prepared.record.nonce,createdAt:new Date(now),updatedAt:new Date(now)});
  if(reason==='receipt')await db.insert(copyFollowerReceipts).values({key:'manual-receipt',accountId:'account',network:'testnet',accountAddress:prepared.intent.accountAddress,kind:'fill',sourceId:'1',coin:'BTC',providerTime:new Date(now),digest:'d'.repeat(64),executionKey:prepared.record.key,attribution:'execution',record:{raw:{}}});
  const before=await financialRows(),id={...identity(),...(reason==='foreign_owner'?{userId:2}:{}),...(reason==='source_scope_wrong'?{source:{network:'testnet' as const,leaderAddress:`0x${'88'.repeat(20)}`}}:{})};if(reason==='source_scope_missing')delete (id as {source?:unknown}).source;
  await expect(scope.run(id,(_s,session)=>recovery.releaseExpired(session,{accountId:'account',key:prepared.record.key,expectedReservationRevision:reason==='wrong_revision'?2:1}))).rejects.toThrow();expect(await financialRows()).toEqual(before);
 });
 it('rolls journal and leg back if the final reservation CAS refuses the write',async()=>{const before=await financialRows();await db.execute(sql`create function reject_expiry_reservation() returns trigger language plpgsql as $$ begin return null; end $$`);await db.execute(sql`create trigger reject_expiry_reservation before update on copy_live_risk_reservations for each row execute function reject_expiry_reservation()`);try{await expect(release()).rejects.toThrow();expect(await financialRows()).toEqual(before);}finally{await db.execute(sql`drop trigger reject_expiry_reservation on copy_live_risk_reservations`);await db.execute(sql`drop function reject_expiry_reservation()`);}});
 it('rejects a copied/ended SQL session rather than acquiring a new connection',async()=>{let old!:LiveRiskDatabaseSession;await scope.run(identity(),async(_s,session)=>{old=session;await expect(recovery.releaseExpired({...session},{accountId:'account',key:prepared.record.key,expectedReservationRevision:1})).rejects.toThrow();});const connect=vi.spyOn(pool,'connect');try{await expect(recovery.releaseExpired(old,{accountId:'account',key:prepared.record.key,expectedReservationRevision:1})).rejects.toThrow();expect(connect).not.toHaveBeenCalled();}finally{connect.mockRestore();}});
});
