/** Shared cache identities. Preserve tuple prefixes used by mutations and SSE. */
export const queryKeys = {
  siteSettings: ["site-settings"] as const,
  crowd: ["crowd"] as const,
  cohort: (tier: string) => ["cohort", tier] as const,
  cohortHistory: (tier: string, window: string) => ["cohort-history", tier, window] as const,
  me: ["me"] as const,
  adminSystem: ["admin", "system"] as const,
  adminHeartbeat: ["admin", "heartbeat"] as const,
  favorites: ["favorites"] as const,
  favoriteGroups: ["favorite-groups"] as const,
  telegram: ["telegram"] as const,
  wallet: {
    all: ["wallet"] as const,
    summary: ["wallet", "summary"] as const,
    history: ["wallet", "history"] as const,
  },
  /** Paper copies: every mutation invalidates `all` (overview + orders). */
  copy: {
    all: ["copy"] as const,
    overview: ["copy", "overview"] as const,
    orders: (strategyId: number) => ["copy", "orders", strategyId] as const,
  },
  traders: {
    all: ["traders"] as const,
    list: (qs: string) => ["traders", qs] as const,
  },
  sparklines: (window: string, addresses: string) => ["sparklines", window, addresses] as const,
  discover: {
    boards: ["discover-board"] as const,
    board: (qs: string) => ["discover-board", qs] as const,
    home: ["discover-home"] as const,
    cards: (addresses: string) => ["discover-cards", addresses] as const,
    coins: ["discover-coins"] as const,
    coin: (coin: string) => ["discover-coin", coin] as const,
    search: (q: string) => ["discover-search", q] as const,
  },
  trader: {
    all: ["trader"] as const,
    profile: (address: string) => ["trader", address] as const,
    activity: (address: string) => ["trader-activity", address] as const,
    portfolio: (address: string, window: string, market: string) => ["portfolio", address, window, market] as const,
    analytics: (address: string, window: string) => ["trader-analytics", address, window] as const,
    trades: (address: string, status: string) => ["trader-trades", address, status] as const,
    orders: (address: string) => ["trader-orders", address] as const,
    twap: (address: string) => ["trader-twap", address] as const,
    transfers: (address: string) => ["trader-transfers", address] as const,
    fills: (address: string, limit: number) => ["trader-fills", address, limit] as const,
    copyScore: (address: string) => ["trader-copy-score", address] as const,
  },
  actions: {
    all: ["actions"] as const,
    list: (qs: string) => ["actions", qs] as const,
    fills: (id: string) => ["action-fills", id] as const,
  },
  alerts: (qs: string) => ["alerts", qs] as const,
  admin: {
    settingsRuntime: ["admin", "settings-runtime"] as const,
    audit: (qs: string) => ["admin", "audit", qs] as const,
    jobs: { all: ["admin", "jobs"] as const, list: (qs: string) => ["admin", "jobs", qs] as const },
    users: {
      all: ["admin", "users"] as const,
      list: (qs: string) => ["admin", "users", qs] as const,
    },
    revenue: (range: string) => ["admin", "revenue", range] as const,
    unresolvedWithdrawals: ["admin", "withdrawals", "unresolved"] as const,
    lists: ["admin", "lists"] as const,
    overview: ["admin", "overview"] as const,
    rules: ["admin", "rules"] as const,
    settings: ["admin", "settings"] as const,
    kols: ["admin", "kols"] as const,
    /** Every copy command and policy save invalidates `all`. */
    copy: {
      all: ["admin", "copy"] as const,
      overview: ["admin", "copy", "overview"] as const,
      exposure: ["admin", "copy", "exposure"] as const,
      risk: ["admin", "copy", "risk"] as const,
      strategies: (qs: string) => ["admin", "copy", "strategies", qs] as const,
      strategy: (id: number) => ["admin", "copy", "strategy", id] as const,
      orders: (qs: string) => ["admin", "copy", "orders", qs] as const,
      live: {
        accounts: ["admin", "copy", "live", "accounts"] as const,
        transfers: ["admin", "copy", "live", "transfers"] as const,
        orders: (state: string) => ["admin", "copy", "live", "orders", state] as const,
        latency: (window: string) => ["admin", "copy", "live", "latency", window] as const,
      },
    },
  },
};
