import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, lstatSync, readlinkSync, realpathSync } from 'node:fs';
import { resolve, relative, isAbsolute } from 'node:path';
import { pathToFileURL } from 'node:url';
export const PROOF_MODULES = Object.freeze([
 'apps/api/dist/copy/copy-live-mandate-evidence.js', 'apps/api/dist/copy/copy-live-mandate-consent.js',
 'apps/api/dist/copy/live/copy-live-source-evidence.js', 'apps/api/dist/copy/live/live-settlement-proof.js',
 'apps/api/dist/copy/live/postgres-live-preparation.js', 'apps/api/dist/copy/live/actual-fill-accounting.js',
 'apps/api/dist/copy/live/live-order.js',
]);
const sha = value => createHash('sha256').update(value).digest('hex');
function safeFile(root, path) {
 if (typeof path !== 'string' || isAbsolute(path) || path.split('/').includes('..')) throw Error('Invalid proof artifact path');
 const full=resolve(root,path), rel=relative(realpathSync(root),realpathSync(full));
 if(rel.startsWith('..')||isAbsolute(rel))throw Error('Proof artifact escapes pinned runtime');
 return full;
}
export function compiledProofFiles(root) {
 const rows=[];
 for(const base of ['apps/api/dist','packages/shared/dist']) {
  const walk=path=>{for(const entry of readdirSync(resolve(root,path),{withFileTypes:true})){
   const file=`${path}/${entry.name}`;
   if(entry.isDirectory())walk(file);
   else if(entry.isFile()&&entry.name.endsWith('.js'))rows.push({path:file,sha256:sha(readFileSync(safeFile(root,file)))});
  }};walk(base);
 }
 return rows.sort((a,b)=>a.path.localeCompare(b.path));
}
export function verifyProofArtifacts(root, manifest, build) {
 root=realpathSync(root);
 if(manifest?.version!==1||manifest.reviewed!==true||manifest.root!==root||manifest.commit!==build?.commit||!/^([a-f0-9]{40})$/.test(manifest.commit)||
  build.status!=='passed'||build.allTrackedBlobsUnchanged!==true||build.envCopied!==false||!Number.isSafeInteger(build.trackedBlobs)||
  manifest.buildSha256!==sha(readFileSync(safeFile(root,'BUILD-EVIDENCE.json')))||build.mainSha256!==sha(readFileSync(safeFile(root,'apps/api/dist/main.js'))))throw Error('Unapproved or inconsistent pinned proof build');
 const files=compiledProofFiles(root);
 if(!Array.isArray(manifest.files)||JSON.stringify(files)!==JSON.stringify(manifest.files)||PROOF_MODULES.some(path=>!files.some(file=>file.path===path)))throw Error('Pinned proof compiled blobs changed');
 const shared=realpathSync(resolve(root,'apps/api/node_modules/@trading-dashboard/shared'));
 if(shared!==realpathSync(resolve(root,'packages/shared')))throw Error('Proof runtime uses foreign shared build');
 return files;
}
export async function loadProofRuntime({root,manifestPath,repositoryRoot,profile,network,leaderNetwork,db,perTradeUsd,maxPerTradeUsd,maxLeverage}) {
 if(profile!=='stage-caps'||network!=='testnet'||leaderNetwork!=='testnet'||db!=='env'||!root||!manifestPath||perTradeUsd!==12||maxPerTradeUsd!==15||maxLeverage!==3)throw Error('Proof runtime requires exact local testnet stage-caps 50/12–15/3 profile');
 const url=new URL(process.env.HARNESS_DATABASE_URL||'');
 if(!['postgres:','postgresql:'].includes(url.protocol)||!['localhost','127.0.0.1','[::1]'].includes(url.hostname))throw Error('Proof runtime requires local database');
 root=realpathSync(root);
 const manifest=JSON.parse(readFileSync(manifestPath,'utf8')),build=JSON.parse(readFileSync(safeFile(root,'BUILD-EVIDENCE.json'),'utf8'));
 const files=verifyProofArtifacts(root,manifest,build);
 const records=execFileSync('git',['ls-tree','-r','-z',build.commit],{cwd:repositoryRoot,encoding:'utf8',maxBuffer:4*1024*1024}).split('\0').filter(Boolean);
 if(records.length!==build.trackedBlobs)throw Error('Pinned source blob count changed');
 for(const record of records){
  const match=/^(100644|100755|120000) blob ([a-f0-9]{40})\t(.+)$/.exec(record);
  if(!match)throw Error('Unsupported pinned source entry');
  const [,mode,expected,path]=match,full=resolve(root,path);
  if(isAbsolute(path)||path.split('/').includes('..'))throw Error('Unsafe pinned source');
  const value=mode==='120000'?Buffer.from(readlinkSync(full)):readFileSync(safeFile(root,path));
  if(mode!=='120000'&&!lstatSync(full).isFile())throw Error('Pinned source entry changed');
  if(createHash('sha1').update(Buffer.from(`blob ${value.length}\0`)).update(value).digest('hex')!==expected)throw Error(`Pinned source blob changed: ${path}`);
 }
 const tools={};
 for(const module of PROOF_MODULES)Object.assign(tools,await import(pathToFileURL(safeFile(root,module)).href));
 // Recheck after imports: no automatic acceptance of a manifest generated by this run.
 verifyProofArtifacts(root,manifest,build);
 return {tools,attestation:{commit:build.commit,root,compiledFiles:files.length,manifestSha256:sha(readFileSync(manifestPath))}};
}
